"""Bazarr tool: create_webhooks_sonarr."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py with Bazarr PATCH support.

@register_tool(
    namespace="bazarr",
    description="State-changing POST /webhooks/sonarr: Search for missing subtitles based on Sonarr webhooks",
    examples=[
        "load_tool(\"bazarr.create_webhooks_sonarr\")(...)",
    ],
    aliases=[],
)
def create_webhooks_sonarr(params: Optional[Dict[str, Any]] = None, body: Optional[Any] = None) -> Any:
    """POST /webhooks/sonarr."""
    client = get_client()
    return client.post('webhooks/sonarr', body=body, params=params)
