"""Bazarr tool: create_episodes_blacklist."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py with Bazarr PATCH support.

@register_tool(
    namespace="bazarr",
    description="State-changing POST /episodes/blacklist: Add an episodes subtitles to blacklist",
    examples=[
        "load_tool(\"bazarr.create_episodes_blacklist\")(...)",
    ],
    aliases=[],
)
def create_episodes_blacklist(params: Optional[Dict[str, Any]] = None, body: Optional[Any] = None) -> Any:
    """POST /episodes/blacklist."""
    client = get_client()
    return client.post('episodes/blacklist', body=body, params=params)
