"""Bazarr tool: create_providers_episodes."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py with Bazarr PATCH support.

@register_tool(
    namespace="bazarr",
    description="State-changing POST /providers/episodes: Manually download an episode subtitles",
    examples=[
        "load_tool(\"bazarr.create_providers_episodes\")(...)",
    ],
    aliases=[],
)
def create_providers_episodes(params: Optional[Dict[str, Any]] = None, body: Optional[Any] = None) -> Any:
    """POST /providers/episodes."""
    client = get_client()
    return client.post('providers/episodes', body=body, params=params)
