"""Bazarr tool: create_webhooks_plex."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py with Bazarr PATCH support.

@register_tool(
    namespace="bazarr",
    description="State-changing POST /webhooks/plex: Trigger subtitles search on play media event in Plex",
    examples=[
        "load_tool(\"bazarr.create_webhooks_plex\")(...)",
    ],
    aliases=[],
)
def create_webhooks_plex(params: Optional[Dict[str, Any]] = None, body: Optional[Any] = None) -> Any:
    """POST /webhooks/plex."""
    client = get_client()
    return client.post('webhooks/plex', body=body, params=params)
