"""Bazarr tool: create_system_tasks."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py with Bazarr PATCH support.

@register_tool(
    namespace="bazarr",
    description="State-changing POST /system/tasks: Run task",
    examples=[
        "load_tool(\"bazarr.create_system_tasks\")(...)",
    ],
    aliases=[],
)
def create_system_tasks(params: Optional[Dict[str, Any]] = None, body: Optional[Any] = None) -> Any:
    """POST /system/tasks."""
    client = get_client()
    return client.post('system/tasks', body=body, params=params)
