"""Bazarr tool: create_plex_apikey."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py with Bazarr PATCH support.

@register_tool(
    namespace="bazarr",
    description="State-changing POST /plex/apikey: POST /plex/apikey",
    examples=[
        "load_tool(\"bazarr.create_plex_apikey\")(...)",
    ],
    aliases=[],
)
def create_plex_apikey(params: Optional[Dict[str, Any]] = None, body: Optional[Any] = None) -> Any:
    """POST /plex/apikey."""
    client = get_client()
    return client.post('plex/apikey', body=body, params=params)
