"""Bazarr tool: create_plex_webhook_delete."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py with Bazarr PATCH support.

@register_tool(
    namespace="bazarr",
    description="State-changing POST /plex/webhook/delete: POST /plex/webhook/delete",
    examples=[
        "load_tool(\"bazarr.create_plex_webhook_delete\")(...)",
    ],
    aliases=[],
)
def create_plex_webhook_delete(params: Optional[Dict[str, Any]] = None, body: Optional[Any] = None) -> Any:
    """POST /plex/webhook/delete."""
    client = get_client()
    return client.post('plex/webhook/delete', body=body, params=params)
