"""Bazarr tool: create_plex_select_server."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py with Bazarr PATCH support.

@register_tool(
    namespace="bazarr",
    description="State-changing POST /plex/select-server: POST /plex/select-server",
    examples=[
        "load_tool(\"bazarr.create_plex_select_server\")(...)",
    ],
    aliases=[],
)
def create_plex_select_server(params: Optional[Dict[str, Any]] = None, body: Optional[Any] = None) -> Any:
    """POST /plex/select-server."""
    client = get_client()
    return client.post('plex/select-server', body=body, params=params)
