"""Bazarr tool: create_system_jobs."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py with Bazarr PATCH support.

@register_tool(
    namespace="bazarr",
    description="State-changing POST /system/jobs: Force start, move to top or move to bottom of the queue a specific job",
    examples=[
        "load_tool(\"bazarr.create_system_jobs\")(...)",
    ],
    aliases=[],
)
def create_system_jobs(params: Optional[Dict[str, Any]] = None, body: Optional[Any] = None) -> Any:
    """POST /system/jobs."""
    client = get_client()
    return client.post('system/jobs', body=body, params=params)
