"""Bazarr tool: create_movies."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py with Bazarr PATCH support.

@register_tool(
    namespace="bazarr",
    description="State-changing POST /movies: Update specific movies languages profile",
    examples=[
        "load_tool(\"bazarr.create_movies\")(...)",
    ],
    aliases=[],
)
def create_movies(params: Optional[Dict[str, Any]] = None, body: Optional[Any] = None) -> Any:
    """POST /movies."""
    client = get_client()
    return client.post('movies', body=body, params=params)
