"""Bazarr tool: create_plex_test_connection."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py with Bazarr PATCH support.

@register_tool(
    namespace="bazarr",
    description="State-changing POST /plex/test-connection: POST /plex/test-connection",
    examples=[
        "load_tool(\"bazarr.create_plex_test_connection\")(...)",
    ],
    aliases=[],
)
def create_plex_test_connection(params: Optional[Dict[str, Any]] = None, body: Optional[Any] = None) -> Any:
    """POST /plex/test-connection."""
    client = get_client()
    return client.post('plex/test-connection', body=body, params=params)
