"""Bazarr tool: delete_system_backups."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py with Bazarr PATCH support.

@register_tool(
    namespace="bazarr",
    description="State-changing DELETE /system/backups: Delete a backup file",
    examples=[
        "load_tool(\"bazarr.delete_system_backups\")(...)",
    ],
    aliases=[],
)
def delete_system_backups(params: Optional[Dict[str, Any]] = None) -> Any:
    """DELETE /system/backups."""
    client = get_client()
    return client.delete('system/backups', params=params)
