"""Bazarr tool: delete_system_logs."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py with Bazarr PATCH support.

@register_tool(
    namespace="bazarr",
    description="State-changing DELETE /system/logs: Force log rotation and create a new log file",
    examples=[
        "load_tool(\"bazarr.delete_system_logs\")(...)",
    ],
    aliases=[],
)
def delete_system_logs(params: Optional[Dict[str, Any]] = None) -> Any:
    """DELETE /system/logs."""
    client = get_client()
    return client.delete('system/logs', params=params)
