"""Bazarr tool: delete_movies_blacklist."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py with Bazarr PATCH support.

@register_tool(
    namespace="bazarr",
    description="State-changing DELETE /movies/blacklist: Delete a movies subtitles from blacklist",
    examples=[
        "load_tool(\"bazarr.delete_movies_blacklist\")(...)",
    ],
    aliases=[],
)
def delete_movies_blacklist(params: Optional[Dict[str, Any]] = None) -> Any:
    """DELETE /movies/blacklist."""
    client = get_client()
    return client.delete('movies/blacklist', params=params)
