"""Bazarr tool: delete_system_jobs."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py with Bazarr PATCH support.

@register_tool(
    namespace="bazarr",
    description="State-changing DELETE /system/jobs: Delete a job from the queue",
    examples=[
        "load_tool(\"bazarr.delete_system_jobs\")(...)",
    ],
    aliases=[],
)
def delete_system_jobs(params: Optional[Dict[str, Any]] = None) -> Any:
    """DELETE /system/jobs."""
    client = get_client()
    return client.delete('system/jobs', params=params)
