"""Bazarr tool: delete_episodes_subtitles."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py with Bazarr PATCH support.

@register_tool(
    namespace="bazarr",
    description="State-changing DELETE /episodes/subtitles: Delete an episode subtitles",
    examples=[
        "load_tool(\"bazarr.delete_episodes_subtitles\")(...)",
    ],
    aliases=[],
)
def delete_episodes_subtitles(params: Optional[Dict[str, Any]] = None) -> Any:
    """DELETE /episodes/subtitles."""
    client = get_client()
    return client.delete('episodes/subtitles', params=params)
