"""Bazarr tool: get_plex_webhook_list."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py with Bazarr PATCH support.

@register_tool(
    namespace="bazarr",
    description="GET /plex/webhook/list: GET /plex/webhook/list",
    examples=[
        "load_tool(\"bazarr.get_plex_webhook_list\")(...)",
    ],
    aliases=[],
)
def get_plex_webhook_list(params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /plex/webhook/list."""
    client = get_client()
    return client.get('plex/webhook/list', params=params)
