"""Bazarr tool: get_files_radarr."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py with Bazarr PATCH support.

@register_tool(
    namespace="bazarr",
    description="GET /files/radarr: List Radarr file system content",
    examples=[
        "load_tool(\"bazarr.get_files_radarr\")(...)",
    ],
    aliases=[],
)
def get_files_radarr(params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /files/radarr."""
    client = get_client()
    return client.get('files/radarr', params=params)
