"""Bazarr tool: get_episodes_wanted."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py with Bazarr PATCH support.

@register_tool(
    namespace="bazarr",
    description="GET /episodes/wanted: List episodes wanted subtitles",
    examples=[
        "load_tool(\"bazarr.get_episodes_wanted\")(...)",
    ],
    aliases=[],
)
def get_episodes_wanted(params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /episodes/wanted."""
    client = get_client()
    return client.get('episodes/wanted', params=params)
