"""Bazarr tool: get_episodes_history."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py with Bazarr PATCH support.

@register_tool(
    namespace="bazarr",
    description="GET /episodes/history: List episodes history events",
    examples=[
        "load_tool(\"bazarr.get_episodes_history\")(...)",
    ],
    aliases=[],
)
def get_episodes_history(params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /episodes/history."""
    client = get_client()
    return client.get('episodes/history', params=params)
