"""Bazarr tool: get_history_stats."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py with Bazarr PATCH support.

@register_tool(
    namespace="bazarr",
    description="GET /history/stats: Get history statistics",
    examples=[
        "load_tool(\"bazarr.get_history_stats\")(...)",
    ],
    aliases=[],
)
def get_history_stats(params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /history/stats."""
    client = get_client()
    return client.get('history/stats', params=params)
