"""Bazarr tool: get_subtitles."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py with Bazarr PATCH support.

@register_tool(
    namespace="bazarr",
    description="GET /subtitles: Return available audio and embedded subtitles tracks with external subtitles",
    examples=[
        "load_tool(\"bazarr.get_subtitles\")(...)",
    ],
    aliases=[],
)
def get_subtitles(params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /subtitles."""
    client = get_client()
    return client.get('subtitles', params=params)
