"""Bazarr tool: get_providers_episodes."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py with Bazarr PATCH support.

@register_tool(
    namespace="bazarr",
    description="GET /providers/episodes: Search manually for an episode subtitles",
    examples=[
        "load_tool(\"bazarr.get_providers_episodes\")(...)",
    ],
    aliases=[],
)
def get_providers_episodes(params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /providers/episodes."""
    client = get_client()
    return client.get('providers/episodes', params=params)
