"""Bazarr tool: get_files."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py with Bazarr PATCH support.

@register_tool(
    namespace="bazarr",
    description="GET /files: List Bazarr file system content",
    examples=[
        "load_tool(\"bazarr.get_files\")(...)",
    ],
    aliases=[],
)
def get_files(params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /files."""
    client = get_client()
    return client.get('files', params=params)
