"""Bazarr tool: get_plex_select_server."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py with Bazarr PATCH support.

@register_tool(
    namespace="bazarr",
    description="GET /plex/select-server: GET /plex/select-server",
    examples=[
        "load_tool(\"bazarr.get_plex_select_server\")(...)",
    ],
    aliases=[],
)
def get_plex_select_server(params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /plex/select-server."""
    client = get_client()
    return client.get('plex/select-server', params=params)
