"""Bazarr tool: get_movies."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py with Bazarr PATCH support.

@register_tool(
    namespace="bazarr",
    description="GET /movies: List movies metadata for specific movies",
    examples=[
        "load_tool(\"bazarr.get_movies\")(...)",
    ],
    aliases=[],
)
def get_movies(params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /movies."""
    client = get_client()
    return client.get('movies', params=params)
