"""Bazarr tool: get_movies_blacklist."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py with Bazarr PATCH support.

@register_tool(
    namespace="bazarr",
    description="GET /movies/blacklist: List blacklisted movies subtitles",
    examples=[
        "load_tool(\"bazarr.get_movies_blacklist\")(...)",
    ],
    aliases=[],
)
def get_movies_blacklist(params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /movies/blacklist."""
    client = get_client()
    return client.get('movies/blacklist', params=params)
