"""Bazarr tool: get_plex_oauth_pin."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py with Bazarr PATCH support.

@register_tool(
    namespace="bazarr",
    description="GET /plex/oauth/pin: GET /plex/oauth/pin",
    examples=[
        "load_tool(\"bazarr.get_plex_oauth_pin\")(...)",
    ],
    aliases=[],
)
def get_plex_oauth_pin(params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /plex/oauth/pin."""
    client = get_client()
    return client.get('plex/oauth/pin', params=params)
