"""Bazarr tool: get_plex_oauth_pin_by_pin_id_check."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py with Bazarr PATCH support.

@register_tool(
    namespace="bazarr",
    description="GET /plex/oauth/pin/{pin_id}/check: GET /plex/oauth/pin/{pin_id}/check",
    examples=[
        "load_tool(\"bazarr.get_plex_oauth_pin_by_pin_id_check\")(...)",
    ],
    aliases=[],
)
def get_plex_oauth_pin_by_pin_id_check(pin_id: str, params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /plex/oauth/pin/{pin_id}/check."""
    client = get_client()
    return client.get(f"plex/oauth/pin/{pin_id}/check", params=params)
