"""Bazarr tool: get_providers."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py with Bazarr PATCH support.

@register_tool(
    namespace="bazarr",
    description="GET /providers: Get providers status",
    examples=[
        "load_tool(\"bazarr.get_providers\")(...)",
    ],
    aliases=[],
)
def get_providers(params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /providers."""
    client = get_client()
    return client.get('providers', params=params)
