"""Bazarr tool: get_plex_oauth_servers."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py with Bazarr PATCH support.

@register_tool(
    namespace="bazarr",
    description="GET /plex/oauth/servers: GET /plex/oauth/servers",
    examples=[
        "load_tool(\"bazarr.get_plex_oauth_servers\")(...)",
    ],
    aliases=[],
)
def get_plex_oauth_servers(params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /plex/oauth/servers."""
    client = get_client()
    return client.get('plex/oauth/servers', params=params)
