"""Bazarr tool: get_plex_test_connection."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py with Bazarr PATCH support.

@register_tool(
    namespace="bazarr",
    description="GET /plex/test-connection: GET /plex/test-connection",
    examples=[
        "load_tool(\"bazarr.get_plex_test_connection\")(...)",
    ],
    aliases=[],
)
def get_plex_test_connection(params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /plex/test-connection."""
    client = get_client()
    return client.get('plex/test-connection', params=params)
