"""Bazarr tool: get_system_jobs."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py with Bazarr PATCH support.

@register_tool(
    namespace="bazarr",
    description="GET /system/jobs: List jobs from the queue",
    examples=[
        "load_tool(\"bazarr.get_system_jobs\")(...)",
    ],
    aliases=[],
)
def get_system_jobs(params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /system/jobs."""
    client = get_client()
    return client.get('system/jobs', params=params)
