"""Bazarr tool: get_plex_autopulse_config."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py with Bazarr PATCH support.

@register_tool(
    namespace="bazarr",
    description="GET /plex/autopulse/config: GET /plex/autopulse/config",
    examples=[
        "load_tool(\"bazarr.get_plex_autopulse_config\")(...)",
    ],
    aliases=[],
)
def get_plex_autopulse_config(params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /plex/autopulse/config."""
    client = get_client()
    return client.get('plex/autopulse/config', params=params)
