"""Bazarr tool: get_subtitles_info."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py with Bazarr PATCH support.

@register_tool(
    namespace="bazarr",
    description="GET /subtitles/info: Guessit over subtitles filename",
    examples=[
        "load_tool(\"bazarr.get_subtitles_info\")(...)",
    ],
    aliases=[],
)
def get_subtitles_info(params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /subtitles/info."""
    client = get_client()
    return client.get('subtitles/info', params=params)
