"""Bazarr tool: get_episodes."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py with Bazarr PATCH support.

@register_tool(
    namespace="bazarr",
    description="GET /episodes: List episodes metadata for specific series or episodes",
    examples=[
        "load_tool(\"bazarr.get_episodes\")(...)",
    ],
    aliases=[],
)
def get_episodes(params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /episodes."""
    client = get_client()
    return client.get('episodes', params=params)
