"""Bazarr tool: get_system_logs."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py with Bazarr PATCH support.

@register_tool(
    namespace="bazarr",
    description="GET /system/logs: List log entries",
    examples=[
        "load_tool(\"bazarr.get_system_logs\")(...)",
    ],
    aliases=[],
)
def get_system_logs(params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /system/logs."""
    client = get_client()
    return client.get('system/logs', params=params)
