"""Bazarr tool: update_series."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py with Bazarr PATCH support.

@register_tool(
    namespace="bazarr",
    description="State-changing PATCH /series: Run actions on specific series",
    examples=[
        "load_tool(\"bazarr.update_series\")(...)",
    ],
    aliases=[],
)
def update_series(params: Optional[Dict[str, Any]] = None, body: Optional[Any] = None) -> Any:
    """PATCH /series."""
    client = get_client()
    return client.patch('series', body=body, params=params)
