"""Bazarr tool: update_subtitles."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py with Bazarr PATCH support.

@register_tool(
    namespace="bazarr",
    description="State-changing PATCH /subtitles: Apply mods/tools on external subtitles",
    examples=[
        "load_tool(\"bazarr.update_subtitles\")(...)",
    ],
    aliases=[],
)
def update_subtitles(params: Optional[Dict[str, Any]] = None, body: Optional[Any] = None) -> Any:
    """PATCH /subtitles."""
    client = get_client()
    return client.patch('subtitles', body=body, params=params)
