"""radarr tool: create_indexer_test."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="radarr",
    description="POST /api/v3/indexer/test",
    examples=[
        "load_tool(\"radarr.create_indexer_test\")(...)",
    ],
    aliases=[],
)
def create_indexer_test(params: Optional[Dict[str, Any]] = None, body: Optional[Any] = None) -> Any:
    """POST /api/v3/indexer/test."""
    client = get_client()
    return client.post('indexer/test', body=body, params=params)
