"""radarr tool: create_queue_grab_by_id."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="radarr",
    description="POST /api/v3/queue/grab/{id}",
    examples=[
        "load_tool(\"radarr.create_queue_grab_by_id\")(...)",
    ],
    aliases=[],
)
def create_queue_grab_by_id(id: int, params: Optional[Dict[str, Any]] = None, body: Optional[Any] = None) -> Any:
    """POST /api/v3/queue/grab/{id}."""
    client = get_client()
    return client.post(f"queue/grab/{id}", body=body, params=params)
