"""radarr tool: create_qualityprofile."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="radarr",
    description="POST /api/v3/qualityprofile",
    examples=[
        "load_tool(\"radarr.create_qualityprofile\")(...)",
    ],
    aliases=[],
)
def create_qualityprofile(params: Optional[Dict[str, Any]] = None, body: Optional[Any] = None) -> Any:
    """POST /api/v3/qualityprofile."""
    client = get_client()
    return client.post('qualityprofile', body=body, params=params)
