"""radarr tool: delete_movie_editor."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="radarr",
    description="DELETE /api/v3/movie/editor",
    examples=[
        "load_tool(\"radarr.delete_movie_editor\")(...)",
    ],
    aliases=[],
)
def delete_movie_editor(params: Optional[Dict[str, Any]] = None) -> Any:
    """DELETE /api/v3/movie/editor."""
    client = get_client()
    return client.delete('movie/editor', params=params)
