"""radarr tool: get_exclusions_paged."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="radarr",
    description="GET /api/v3/exclusions/paged",
    examples=[
        "load_tool(\"radarr.get_exclusions_paged\")(...)",
    ],
    aliases=[],
)
def get_exclusions_paged(params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /api/v3/exclusions/paged."""
    client = get_client()
    return client.get('exclusions/paged', params=params)
