"""radarr tool: get_qualitydefinition_limits."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="radarr",
    description="GET /api/v3/qualitydefinition/limits",
    examples=[
        "load_tool(\"radarr.get_qualitydefinition_limits\")(...)",
    ],
    aliases=[],
)
def get_qualitydefinition_limits(params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /api/v3/qualitydefinition/limits."""
    client = get_client()
    return client.get('qualitydefinition/limits', params=params)
