"""radarr tool: get_customfilter_by_id."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="radarr",
    description="GET /api/v3/customfilter/{id}",
    examples=[
        "load_tool(\"radarr.get_customfilter_by_id\")(...)",
    ],
    aliases=[],
)
def get_customfilter_by_id(id: int, params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /api/v3/customfilter/{id}."""
    client = get_client()
    return client.get(f"customfilter/{id}", params=params)
