"""radarr tool: get_tag_detail."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="radarr",
    description="GET /api/v3/tag/detail",
    examples=[
        "load_tool(\"radarr.get_tag_detail\")(...)",
    ],
    aliases=[],
)
def get_tag_detail(params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /api/v3/tag/detail."""
    client = get_client()
    return client.get('tag/detail', params=params)
