"""radarr tool: update_releaseprofile_by_id."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="radarr",
    description="PUT /api/v3/releaseprofile/{id}",
    examples=[
        "load_tool(\"radarr.update_releaseprofile_by_id\")(...)",
    ],
    aliases=[],
)
def update_releaseprofile_by_id(id: str, params: Optional[Dict[str, Any]] = None, body: Optional[Any] = None) -> Any:
    """PUT /api/v3/releaseprofile/{id}."""
    client = get_client()
    return client.put(f"releaseprofile/{id}", body=body, params=params)
