"""radarr tool: update_importlist_bulk."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="radarr",
    description="PUT /api/v3/importlist/bulk",
    examples=[
        "load_tool(\"radarr.update_importlist_bulk\")(...)",
    ],
    aliases=[],
)
def update_importlist_bulk(params: Optional[Dict[str, Any]] = None, body: Optional[Any] = None) -> Any:
    """PUT /api/v3/importlist/bulk."""
    client = get_client()
    return client.put('importlist/bulk', body=body, params=params)
