"""tautulli tool: create_download_plex_log."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="tautulli",
    description="Download the Plex log file.",
    examples=[
        "load_tool(\"tautulli.create_download_plex_log\")(...)",
    ],
    aliases=[],
)
def create_download_plex_log(params: Optional[Dict[str, Any]] = None, body: Optional[Any] = None) -> Any:
    """POST /api/v2/download_plex_log."""
    client = get_client()
    return client.post('download_plex_log', body=body, params=params)
