"""tautulli tool: create_notify."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="tautulli",
    description="Send a notification using Tautulli.",
    examples=[
        "load_tool(\"tautulli.create_notify\")(...)",
    ],
    aliases=[],
)
def create_notify(params: Optional[Dict[str, Any]] = None, body: Optional[Any] = None) -> Any:
    """POST /api/v2/notify."""
    client = get_client()
    return client.post('notify', body=body, params=params)
