"""tautulli tool: create_register_device."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="tautulli",
    description="Registers the Tautulli Remote App.",
    examples=[
        "load_tool(\"tautulli.create_register_device\")(...)",
    ],
    aliases=[],
)
def create_register_device(params: Optional[Dict[str, Any]] = None, body: Optional[Any] = None) -> Any:
    """POST /api/v2/register_device."""
    client = get_client()
    return client.post('register_device', body=body, params=params)
