"""tautulli tool: create_search."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="tautulli",
    description="Get search results from the PMS.",
    examples=[
        "load_tool(\"tautulli.create_search\")(...)",
    ],
    aliases=[],
)
def create_search(params: Optional[Dict[str, Any]] = None, body: Optional[Any] = None) -> Any:
    """POST /api/v2/search."""
    client = get_client()
    return client.post('search', body=body, params=params)
