"""tautulli tool: create_docs."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="tautulli",
    description="Return the api docs as a dict where commands are keys, docstring are value.",
    examples=[
        "load_tool(\"tautulli.create_docs\")(...)",
    ],
    aliases=[],
)
def create_docs(params: Optional[Dict[str, Any]] = None, body: Optional[Any] = None) -> Any:
    """POST /api/v2/docs."""
    client = get_client()
    return client.post('docs', body=body, params=params)
