"""tautulli tool: create_restart."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="tautulli",
    description="Restart Tautulli.",
    examples=[
        "load_tool(\"tautulli.create_restart\")(...)",
    ],
    aliases=[],
)
def create_restart(params: Optional[Dict[str, Any]] = None, body: Optional[Any] = None) -> Any:
    """POST /api/v2/restart."""
    client = get_client()
    return client.post('restart', body=body, params=params)
