"""tautulli tool: create_regroup_history."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="tautulli",
    description="Regroup play history in the database.",
    examples=[
        "load_tool(\"tautulli.create_regroup_history\")(...)",
    ],
    aliases=[],
)
def create_regroup_history(params: Optional[Dict[str, Any]] = None, body: Optional[Any] = None) -> Any:
    """POST /api/v2/regroup_history."""
    client = get_client()
    return client.post('regroup_history', body=body, params=params)
