"""tautulli tool: create_refresh_users_list."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="tautulli",
    description="Refresh the Tautulli users list.",
    examples=[
        "load_tool(\"tautulli.create_refresh_users_list\")(...)",
    ],
    aliases=[],
)
def create_refresh_users_list(params: Optional[Dict[str, Any]] = None, body: Optional[Any] = None) -> Any:
    """POST /api/v2/refresh_users_list."""
    client = get_client()
    return client.post('refresh_users_list', body=body, params=params)
