"""tautulli tool: delete_delete_recently_added."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="tautulli",
    description="Flush out all of the recently added items in the database.",
    examples=[
        "load_tool(\"tautulli.delete_delete_recently_added\")(...)",
    ],
    aliases=[],
)
def delete_delete_recently_added(params: Optional[Dict[str, Any]] = None) -> Any:
    """DELETE /api/v2/delete_recently_added."""
    client = get_client()
    return client.delete('delete_recently_added', params=params)
