"""tautulli tool: delete_delete_lookup_info."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="tautulli",
    description="Delete the 3rd party API lookup info.",
    examples=[
        "load_tool(\"tautulli.delete_delete_lookup_info\")(...)",
    ],
    aliases=[],
)
def delete_delete_lookup_info(params: Optional[Dict[str, Any]] = None) -> Any:
    """DELETE /api/v2/delete_lookup_info."""
    client = get_client()
    return client.delete('delete_lookup_info', params=params)
