"""tautulli tool: get_get_stream_type_by_top_10_platforms."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="tautulli",
    description="Get graph data by stream type by top 10 platforms.",
    examples=[
        "load_tool(\"tautulli.get_get_stream_type_by_top_10_platforms\")(...)",
    ],
    aliases=[],
)
def get_get_stream_type_by_top_10_platforms(params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /api/v2/get_stream_type_by_top_10_platforms."""
    client = get_client()
    return client.get('get_stream_type_by_top_10_platforms', params=params)
