"""tautulli tool: get_arnold."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="tautulli",
    description="Get to the chopper!",
    examples=[
        "load_tool(\"tautulli.get_arnold\")(...)",
    ],
    aliases=[],
)
def get_arnold(params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /api/v2/arnold."""
    client = get_client()
    return client.get('arnold', params=params)
