"""tautulli tool: get_status."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="tautulli",
    description="Get the current status of Tautulli.",
    examples=[
        "load_tool(\"tautulli.get_status\")(...)",
    ],
    aliases=[],
)
def get_status(params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /api/v2/status."""
    client = get_client()
    return client.get('status', params=params)
