"""tautulli tool: get_get_tautulli_info."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="tautulli",
    description="Get info about the Tautulli server.",
    examples=[
        "load_tool(\"tautulli.get_get_tautulli_info\")(...)",
    ],
    aliases=[],
)
def get_get_tautulli_info(params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /api/v2/get_tautulli_info."""
    client = get_client()
    return client.get('get_tautulli_info', params=params)
