"""tautulli tool: get_get_exports_table."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="tautulli",
    description="Get the data on the Tautulli export tables.",
    examples=[
        "load_tool(\"tautulli.get_get_exports_table\")(...)",
    ],
    aliases=[],
)
def get_get_exports_table(params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /api/v2/get_exports_table."""
    client = get_client()
    return client.get('get_exports_table', params=params)
