"""tautulli tool: update_set_newsletter_config."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="tautulli",
    description="Configure an existing newsletter agent.",
    examples=[
        "load_tool(\"tautulli.update_set_newsletter_config\")(...)",
    ],
    aliases=[],
)
def update_set_newsletter_config(params: Optional[Dict[str, Any]] = None, body: Optional[Any] = None) -> Any:
    """PUT /api/v2/set_newsletter_config."""
    client = get_client()
    return client.put('set_newsletter_config', body=body, params=params)
