"""tautulli tool: update_update_metadata_details."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="tautulli",
    description="Update the metadata in the Tautulli database by matching rating keys.",
    examples=[
        "load_tool(\"tautulli.update_update_metadata_details\")(...)",
    ],
    aliases=[],
)
def update_update_metadata_details(params: Optional[Dict[str, Any]] = None, body: Optional[Any] = None) -> Any:
    """PUT /api/v2/update_metadata_details."""
    client = get_client()
    return client.put('update_metadata_details', body=body, params=params)
