"""Sonarr tool: create_importlist_test."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by tools/sonarr/generate_tools.py.

@register_tool(
    namespace="sonarr",
    description="POST /api/v3/importlist/test",
    examples=[
        "load_tool(\"sonarr.create_importlist_test\")(...)",
    ],
    aliases=[],
)
def create_importlist_test(params: Optional[Dict[str, Any]] = None, body: Optional[Any] = None) -> Any:
    """POST /api/v3/importlist/test."""
    client = get_client()
    return client.post('importlist/test', body=body, params=params)
