"""Sonarr tool: create_queue_grab_bulk."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by tools/sonarr/generate_tools.py.

@register_tool(
    namespace="sonarr",
    description="POST /api/v3/queue/grab/bulk",
    examples=[
        "load_tool(\"sonarr.create_queue_grab_bulk\")(...)",
    ],
    aliases=[],
)
def create_queue_grab_bulk(params: Optional[Dict[str, Any]] = None, body: Optional[Any] = None) -> Any:
    """POST /api/v3/queue/grab/bulk."""
    client = get_client()
    return client.post('queue/grab/bulk', body=body, params=params)
