"""Sonarr tool: create_indexer_testall."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by tools/sonarr/generate_tools.py.

@register_tool(
    namespace="sonarr",
    description="POST /api/v3/indexer/testall",
    examples=[
        "load_tool(\"sonarr.create_indexer_testall\")(...)",
    ],
    aliases=[],
)
def create_indexer_testall(params: Optional[Dict[str, Any]] = None, body: Optional[Any] = None) -> Any:
    """POST /api/v3/indexer/testall."""
    client = get_client()
    return client.post('indexer/testall', body=body, params=params)
