"""Sonarr tool: create_importlist_action_by_name."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by tools/sonarr/generate_tools.py.

@register_tool(
    namespace="sonarr",
    description="POST /api/v3/importlist/action/{name}",
    examples=[
        "load_tool(\"sonarr.create_importlist_action_by_name\")(...)",
    ],
    aliases=[],
)
def create_importlist_action_by_name(name: str, params: Optional[Dict[str, Any]] = None, body: Optional[Any] = None) -> Any:
    """POST /api/v3/importlist/action/{name}."""
    client = get_client()
    return client.post(f"importlist/action/{name}", body=body, params=params)
