"""Sonarr tool: create_remotepathmapping."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by tools/sonarr/generate_tools.py.

@register_tool(
    namespace="sonarr",
    description="POST /api/v3/remotepathmapping",
    examples=[
        "load_tool(\"sonarr.create_remotepathmapping\")(...)",
    ],
    aliases=[],
)
def create_remotepathmapping(params: Optional[Dict[str, Any]] = None, body: Optional[Any] = None) -> Any:
    """POST /api/v3/remotepathmapping."""
    client = get_client()
    return client.post('remotepathmapping', body=body, params=params)
