"""Sonarr tool: delete_series_by_id."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by tools/sonarr/generate_tools.py.

@register_tool(
    namespace="sonarr",
    description="DELETE /api/v3/series/{id}",
    examples=[
        "load_tool(\"sonarr.delete_series_by_id\")(...)",
    ],
    aliases=["sonarr.delete_series", "delete_series"],
)
def delete_series_by_id(id: int, params: Optional[Dict[str, Any]] = None) -> Any:
    """DELETE /api/v3/series/{id}."""
    client = get_client()
    return client.delete(f"series/{id}", params=params)
