"""Sonarr tool: delete_series_editor."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by tools/sonarr/generate_tools.py.

@register_tool(
    namespace="sonarr",
    description="DELETE /api/v3/series/editor",
    examples=[
        "load_tool(\"sonarr.delete_series_editor\")(...)",
    ],
    aliases=[],
)
def delete_series_editor(params: Optional[Dict[str, Any]] = None) -> Any:
    """DELETE /api/v3/series/editor."""
    client = get_client()
    return client.delete('series/editor', params=params)
