"""Sonarr tool: get_series_lookup."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by tools/sonarr/generate_tools.py.

@register_tool(
    namespace="sonarr",
    description="GET /api/v3/series/lookup",
    examples=[
        "load_tool(\"sonarr.get_series_lookup\")(...)",
    ],
    aliases=["sonarr.lookup_series", "lookup_series"],
)
def get_series_lookup(params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /api/v3/series/lookup."""
    client = get_client()
    return client.get('series/lookup', params=params)
