"""Sonarr tool: get_rootfolder."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by tools/sonarr/generate_tools.py.

@register_tool(
    namespace="sonarr",
    description="GET /api/v3/rootfolder",
    examples=[
        "load_tool(\"sonarr.get_rootfolder\")(...)",
    ],
    aliases=["sonarr.get_root_folders", "get_root_folders"],
)
def get_rootfolder(params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /api/v3/rootfolder."""
    client = get_client()
    return client.get('rootfolder', params=params)
