"""Sonarr tool: get_parse."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by tools/sonarr/generate_tools.py.

@register_tool(
    namespace="sonarr",
    description="GET /api/v3/parse",
    examples=[
        "load_tool(\"sonarr.get_parse\")(...)",
    ],
    aliases=[],
)
def get_parse(params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /api/v3/parse."""
    client = get_client()
    return client.get('parse', params=params)
