"""Sonarr tool: get_queue_details."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by tools/sonarr/generate_tools.py.

@register_tool(
    namespace="sonarr",
    description="GET /api/v3/queue/details",
    examples=[
        "load_tool(\"sonarr.get_queue_details\")(...)",
    ],
    aliases=[],
)
def get_queue_details(params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /api/v3/queue/details."""
    client = get_client()
    return client.get('queue/details', params=params)
