"""Sonarr tool: get_config_host."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by tools/sonarr/generate_tools.py.

@register_tool(
    namespace="sonarr",
    description="GET /api/v3/config/host",
    examples=[
        "load_tool(\"sonarr.get_config_host\")(...)",
    ],
    aliases=[],
)
def get_config_host(params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /api/v3/config/host."""
    client = get_client()
    return client.get('config/host', params=params)
