"""Sonarr tool: get_qualityprofile."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by tools/sonarr/generate_tools.py.

@register_tool(
    namespace="sonarr",
    description="GET /api/v3/qualityprofile",
    examples=[
        "load_tool(\"sonarr.get_qualityprofile\")(...)",
    ],
    aliases=["sonarr.get_quality_profiles", "get_quality_profiles"],
)
def get_qualityprofile(params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /api/v3/qualityprofile."""
    client = get_client()
    return client.get('qualityprofile', params=params)
