"""Sonarr tool: get_importlistexclusion_paged."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by tools/sonarr/generate_tools.py.

@register_tool(
    namespace="sonarr",
    description="GET /api/v3/importlistexclusion/paged",
    examples=[
        "load_tool(\"sonarr.get_importlistexclusion_paged\")(...)",
    ],
    aliases=[],
)
def get_importlistexclusion_paged(params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /api/v3/importlistexclusion/paged."""
    client = get_client()
    return client.get('importlistexclusion/paged', params=params)
