"""Sonarr tool: get_customfilter."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by tools/sonarr/generate_tools.py.

@register_tool(
    namespace="sonarr",
    description="GET /api/v3/customfilter",
    examples=[
        "load_tool(\"sonarr.get_customfilter\")(...)",
    ],
    aliases=[],
)
def get_customfilter(params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /api/v3/customfilter."""
    client = get_client()
    return client.get('customfilter', params=params)
