"""Sonarr tool: get_qualityprofile_by_id."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by tools/sonarr/generate_tools.py.

@register_tool(
    namespace="sonarr",
    description="GET /api/v3/qualityprofile/{id}",
    examples=[
        "load_tool(\"sonarr.get_qualityprofile_by_id\")(...)",
    ],
    aliases=[],
)
def get_qualityprofile_by_id(id: int, params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /api/v3/qualityprofile/{id}."""
    client = get_client()
    return client.get(f"qualityprofile/{id}", params=params)
