"""Sonarr tool: get_releaseprofile."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by tools/sonarr/generate_tools.py.

@register_tool(
    namespace="sonarr",
    description="GET /api/v3/releaseprofile",
    examples=[
        "load_tool(\"sonarr.get_releaseprofile\")(...)",
    ],
    aliases=[],
)
def get_releaseprofile(params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /api/v3/releaseprofile."""
    client = get_client()
    return client.get('releaseprofile', params=params)
