"""Sonarr tool: head_ping."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by tools/sonarr/generate_tools.py.

@register_tool(
    namespace="sonarr",
    description="HEAD /ping",
    examples=[
        "load_tool(\"sonarr.head_ping\")(...)",
    ],
    aliases=[],
)
def head_ping(params: Optional[Dict[str, Any]] = None) -> Any:
    """HEAD /ping."""
    client = get_client()
    return client.head('ping', params=params, api_path='')
