"""Sonarr tool: update_episode_monitor."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by tools/sonarr/generate_tools.py.

@register_tool(
    namespace="sonarr",
    description="PUT /api/v3/episode/monitor",
    examples=[
        "load_tool(\"sonarr.update_episode_monitor\")(...)",
    ],
    aliases=[],
)
def update_episode_monitor(params: Optional[Dict[str, Any]] = None, body: Optional[Any] = None) -> Any:
    """PUT /api/v3/episode/monitor."""
    client = get_client()
    return client.put('episode/monitor', body=body, params=params)
