"""Sonarr tool: update_series_editor."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by tools/sonarr/generate_tools.py.

@register_tool(
    namespace="sonarr",
    description="PUT /api/v3/series/editor",
    examples=[
        "load_tool(\"sonarr.update_series_editor\")(...)",
    ],
    aliases=[],
)
def update_series_editor(params: Optional[Dict[str, Any]] = None, body: Optional[Any] = None) -> Any:
    """PUT /api/v3/series/editor."""
    client = get_client()
    return client.put('series/editor', body=body, params=params)
