"""prowlarr tool: create_notification_testall."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.
# Post-processed for the nexus_tools_prowlarr package and prowlarr namespace.

@register_tool(
    namespace="prowlarr",
    description="POST /api/v1/notification/testall. State-changing: creates, starts, tests, restores, searches, or triggers the requested Prowlarr operation.",
    examples=[
        "load_tool(\"prowlarr.create_notification_testall\")(...)",
    ],
    aliases=[],
)
def create_notification_testall(params: Optional[Dict[str, Any]] = None, body: Optional[Any] = None) -> Any:
    """POST /api/v1/notification/testall."""
    client = get_client()
    return client.post('notification/testall', body=body, params=params)
