"""prowlarr tool: create_system_backup_restore_by_id."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.
# Post-processed for the nexus_tools_prowlarr package and prowlarr namespace.

@register_tool(
    namespace="prowlarr",
    description="POST /api/v1/system/backup/restore/{id}. State-changing: creates, starts, tests, restores, searches, or triggers the requested Prowlarr operation.",
    examples=[
        "load_tool(\"prowlarr.create_system_backup_restore_by_id\")(...)",
    ],
    aliases=[],
)
def create_system_backup_restore_by_id(id: int, params: Optional[Dict[str, Any]] = None, body: Optional[Any] = None) -> Any:
    """POST /api/v1/system/backup/restore/{id}."""
    client = get_client()
    return client.post(f"system/backup/restore/{id}", body=body, params=params)
