"""prowlarr tool: delete_indexer_bulk."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.
# Post-processed for the nexus_tools_prowlarr package and prowlarr namespace.

@register_tool(
    namespace="prowlarr",
    description="DELETE /api/v1/indexer/bulk. Destructive: removes or clears matching Prowlarr resource(s).",
    examples=[
        "load_tool(\"prowlarr.delete_indexer_bulk\")(...)",
    ],
    aliases=[],
)
def delete_indexer_bulk(params: Optional[Dict[str, Any]] = None) -> Any:
    """DELETE /api/v1/indexer/bulk."""
    client = get_client()
    return client.delete('indexer/bulk', params=params)
