"""prowlarr tool: get."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.
# Post-processed for the nexus_tools_prowlarr package and prowlarr namespace.

@register_tool(
    namespace="prowlarr",
    description="GET /.",
    examples=[
        "load_tool(\"prowlarr.get\")(...)",
    ],
    aliases=[],
)
def get(params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /."""
    client = get_client()
    return client.get('', params=params, api_path='')
