"""prowlarr tool: get_system_status."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.
# Post-processed for the nexus_tools_prowlarr package and prowlarr namespace.

@register_tool(
    namespace="prowlarr",
    description="GET /api/v1/system/status.",
    examples=[
        "load_tool(\"prowlarr.get_system_status\")(...)",
    ],
    aliases=[],
)
def get_system_status(params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /api/v1/system/status."""
    client = get_client()
    return client.get('system/status', params=params)
