"""prowlarr tool: get_log."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.
# Post-processed for the nexus_tools_prowlarr package and prowlarr namespace.

@register_tool(
    namespace="prowlarr",
    description="GET /api/v1/log.",
    examples=[
        "load_tool(\"prowlarr.get_log\")(...)",
    ],
    aliases=[],
)
def get_log(params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /api/v1/log."""
    client = get_client()
    return client.get('log', params=params)
