"""prowlarr tool: get_by_path."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.
# Post-processed for the nexus_tools_prowlarr package and prowlarr namespace.

@register_tool(
    namespace="prowlarr",
    description="GET /{path}.",
    examples=[
        "load_tool(\"prowlarr.get_by_path\")(...)",
    ],
    aliases=[],
)
def get_by_path(path: str, params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /{path}."""
    client = get_client()
    return client.get(f"{path}", params=params, api_path='')
