"""prowlarr tool: get_logout."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.
# Post-processed for the nexus_tools_prowlarr package and prowlarr namespace.

@register_tool(
    namespace="prowlarr",
    description="GET /logout.",
    examples=[
        "load_tool(\"prowlarr.get_logout\")(...)",
    ],
    aliases=[],
)
def get_logout(params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /logout."""
    client = get_client()
    return client.get('logout', params=params, api_path='')
