"""prowlarr tool: get_indexerproxy_by_id."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.
# Post-processed for the nexus_tools_prowlarr package and prowlarr namespace.

@register_tool(
    namespace="prowlarr",
    description="GET /api/v1/indexerproxy/{id}.",
    examples=[
        "load_tool(\"prowlarr.get_indexerproxy_by_id\")(...)",
    ],
    aliases=[],
)
def get_indexerproxy_by_id(id: int, params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /api/v1/indexerproxy/{id}."""
    client = get_client()
    return client.get(f"indexerproxy/{id}", params=params)
