"""prowlarr tool: get_by_id_api."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.
# Post-processed for the nexus_tools_prowlarr package and prowlarr namespace.

@register_tool(
    namespace="prowlarr",
    description="GET /{id}/api.",
    examples=[
        "load_tool(\"prowlarr.get_by_id_api\")(...)",
    ],
    aliases=[],
)
def get_by_id_api(id: int, params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /{id}/api."""
    client = get_client()
    return client.get(f"{id}/api", params=params, api_path='')
