"""prowlarr tool: update_config_development_by_id."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.
# Post-processed for the nexus_tools_prowlarr package and prowlarr namespace.

@register_tool(
    namespace="prowlarr",
    description="PUT /api/v1/config/development/{id}. State-changing: updates matching Prowlarr resource(s).",
    examples=[
        "load_tool(\"prowlarr.update_config_development_by_id\")(...)",
    ],
    aliases=[],
)
def update_config_development_by_id(id: str, params: Optional[Dict[str, Any]] = None, body: Optional[Any] = None) -> Any:
    """PUT /api/v1/config/development/{id}."""
    client = get_client()
    return client.put(f"config/development/{id}", body=body, params=params)
