"""tautulli tool: create_notify_newsletter."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="tautulli",
    description="Send a newsletter using Tautulli.",
    examples=[
        "load_tool(\"tautulli.create_notify_newsletter\")(...)",
    ],
    aliases=[],
)
def create_notify_newsletter(params: Optional[Dict[str, Any]] = None, body: Optional[Any] = None) -> Any:
    """POST /api/v2/notify_newsletter."""
    client = get_client()
    return client.post('notify_newsletter', body=body, params=params)
