"""tautulli tool: create_undelete_library."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="tautulli",
    description="Restore a deleted library section to Tautulli.",
    examples=[
        "load_tool(\"tautulli.create_undelete_library\")(...)",
    ],
    aliases=[],
)
def create_undelete_library(params: Optional[Dict[str, Any]] = None, body: Optional[Any] = None) -> Any:
    """POST /api/v2/undelete_library."""
    client = get_client()
    return client.post('undelete_library', body=body, params=params)
