"""tautulli tool: create_export_metadata."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="tautulli",
    description="Export library or media metadata to a file",
    examples=[
        "load_tool(\"tautulli.create_export_metadata\")(...)",
    ],
    aliases=[],
)
def create_export_metadata(params: Optional[Dict[str, Any]] = None, body: Optional[Any] = None) -> Any:
    """POST /api/v2/export_metadata."""
    client = get_client()
    return client.post('export_metadata', body=body, params=params)
