"""tautulli tool: create_terminate_session."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="tautulli",
    description="Stop a streaming session.",
    examples=[
        "load_tool(\"tautulli.create_terminate_session\")(...)",
    ],
    aliases=[],
)
def create_terminate_session(params: Optional[Dict[str, Any]] = None, body: Optional[Any] = None) -> Any:
    """POST /api/v2/terminate_session."""
    client = get_client()
    return client.post('terminate_session', body=body, params=params)
