"""tautulli tool: create_docs_md."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="tautulli",
    description="Return the api docs formatted with markdown.",
    examples=[
        "load_tool(\"tautulli.create_docs_md\")(...)",
    ],
    aliases=[],
)
def create_docs_md(params: Optional[Dict[str, Any]] = None, body: Optional[Any] = None) -> Any:
    """POST /api/v2/docs_md."""
    client = get_client()
    return client.post('docs_md', body=body, params=params)
