"""tautulli tool: create_server_status."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="tautulli",
    description="Get the current status of Tautulli's connection to the Plex server.",
    examples=[
        "load_tool(\"tautulli.create_server_status\")(...)",
    ],
    aliases=[],
)
def create_server_status(params: Optional[Dict[str, Any]] = None, body: Optional[Any] = None) -> Any:
    """POST /api/v2/server_status."""
    client = get_client()
    return client.post('server_status', body=body, params=params)
