"""tautulli tool: create_pms_image_proxy."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="tautulli",
    description="Gets an image from the PMS and saves it to the image cache directory.",
    examples=[
        "load_tool(\"tautulli.create_pms_image_proxy\")(...)",
    ],
    aliases=[],
)
def create_pms_image_proxy(params: Optional[Dict[str, Any]] = None, body: Optional[Any] = None) -> Any:
    """POST /api/v2/pms_image_proxy."""
    client = get_client()
    return client.post('pms_image_proxy', body=body, params=params)
