"""tautulli tool: create_sql."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="tautulli",
    description="Query the Tautulli database with raw SQL. Automatically makes a backup of",
    examples=[
        "load_tool(\"tautulli.create_sql\")(...)",
    ],
    aliases=[],
)
def create_sql(params: Optional[Dict[str, Any]] = None, body: Optional[Any] = None) -> Any:
    """POST /api/v2/sql."""
    client = get_client()
    return client.post('sql', body=body, params=params)
