"""tautulli tool: create_update."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="tautulli",
    description="Update Tautulli.",
    examples=[
        "load_tool(\"tautulli.create_update\")(...)",
    ],
    aliases=[],
)
def create_update(params: Optional[Dict[str, Any]] = None, body: Optional[Any] = None) -> Any:
    """POST /api/v2/update."""
    client = get_client()
    return client.post('update', body=body, params=params)
