"""tautulli tool: create_backup_db."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="tautulli",
    description="Create a manual backup of the `plexpy.db` file.",
    examples=[
        "load_tool(\"tautulli.create_backup_db\")(...)",
    ],
    aliases=[],
)
def create_backup_db(params: Optional[Dict[str, Any]] = None, body: Optional[Any] = None) -> Any:
    """POST /api/v2/backup_db."""
    client = get_client()
    return client.post('backup_db', body=body, params=params)
