"""tautulli tool: create_import_database."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="tautulli",
    description="Import a Tautulli, PlexWatch, or Plexivity database into Tautulli.",
    examples=[
        "load_tool(\"tautulli.create_import_database\")(...)",
    ],
    aliases=[],
)
def create_import_database(params: Optional[Dict[str, Any]] = None, body: Optional[Any] = None) -> Any:
    """POST /api/v2/import_database."""
    client = get_client()
    return client.post('import_database', body=body, params=params)
