"""tautulli tool: delete_delete_hosted_images."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="tautulli",
    description="Delete the images uploaded to image hosting services.",
    examples=[
        "load_tool(\"tautulli.delete_delete_hosted_images\")(...)",
    ],
    aliases=[],
)
def delete_delete_hosted_images(params: Optional[Dict[str, Any]] = None) -> Any:
    """DELETE /api/v2/delete_hosted_images."""
    client = get_client()
    return client.delete('delete_hosted_images', params=params)
