"""tautulli tool: delete_delete_all_user_history."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="tautulli",
    description="Delete all Tautulli history for a specific user.",
    examples=[
        "load_tool(\"tautulli.delete_delete_all_user_history\")(...)",
    ],
    aliases=[],
)
def delete_delete_all_user_history(params: Optional[Dict[str, Any]] = None) -> Any:
    """DELETE /api/v2/delete_all_user_history."""
    client = get_client()
    return client.delete('delete_all_user_history', params=params)
