"""tautulli tool: delete_delete_media_info_cache."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="tautulli",
    description="Delete the media info table cache for a specific library.",
    examples=[
        "load_tool(\"tautulli.delete_delete_media_info_cache\")(...)",
    ],
    aliases=[],
)
def delete_delete_media_info_cache(params: Optional[Dict[str, Any]] = None) -> Any:
    """DELETE /api/v2/delete_media_info_cache."""
    client = get_client()
    return client.delete('delete_media_info_cache', params=params)
