"""tautulli tool: get_get_whois_lookup."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="tautulli",
    description="Get the connection info for an IP address.",
    examples=[
        "load_tool(\"tautulli.get_get_whois_lookup\")(...)",
    ],
    aliases=[],
)
def get_get_whois_lookup(params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /api/v2/get_whois_lookup."""
    client = get_client()
    return client.get('get_whois_lookup', params=params)
