"""tautulli tool: get_get_pms_update."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="tautulli",
    description="Check for updates to the Plex Media Server.",
    examples=[
        "load_tool(\"tautulli.get_get_pms_update\")(...)",
    ],
    aliases=[],
)
def get_get_pms_update(params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /api/v2/get_pms_update."""
    client = get_client()
    return client.get('get_pms_update', params=params)
