"""tautulli tool: get_get_notifier_parameters."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="tautulli",
    description="Get the list of available notification parameters.",
    examples=[
        "load_tool(\"tautulli.get_get_notifier_parameters\")(...)",
    ],
    aliases=[],
)
def get_get_notifier_parameters(params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /api/v2/get_notifier_parameters."""
    client = get_client()
    return client.get('get_notifier_parameters', params=params)
