"""tautulli tool: get_get_history."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="tautulli",
    description="Get the Tautulli history.",
    examples=[
        "load_tool(\"tautulli.get_get_history\")(...)",
    ],
    aliases=[],
)
def get_get_history(params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /api/v2/get_history."""
    client = get_client()
    return client.get('get_history', params=params)
