"""tautulli tool: get_get_concurrent_streams_by_stream_type."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="tautulli",
    description="Get graph data for concurrent streams by stream type by date.",
    examples=[
        "load_tool(\"tautulli.get_get_concurrent_streams_by_stream_type\")(...)",
    ],
    aliases=[],
)
def get_get_concurrent_streams_by_stream_type(params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /api/v2/get_concurrent_streams_by_stream_type."""
    client = get_client()
    return client.get('get_concurrent_streams_by_stream_type', params=params)
