"""tautulli tool: get_get_new_rating_keys."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="tautulli",
    description="Get a list of new rating keys for the PMS of all of the item's parent/children.",
    examples=[
        "load_tool(\"tautulli.get_get_new_rating_keys\")(...)",
    ],
    aliases=[],
)
def get_get_new_rating_keys(params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /api/v2/get_new_rating_keys."""
    client = get_client()
    return client.get('get_new_rating_keys', params=params)
