"""tautulli tool: get_get_stream_data."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="tautulli",
    description="Get the stream details from history or current stream.",
    examples=[
        "load_tool(\"tautulli.get_get_stream_data\")(...)",
    ],
    aliases=[],
)
def get_get_stream_data(params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /api/v2/get_stream_data."""
    client = get_client()
    return client.get('get_stream_data', params=params)
