"""tautulli tool: get_get_newsletter_log."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="tautulli",
    description="Get the data on the Tautulli newsletter logs table.",
    examples=[
        "load_tool(\"tautulli.get_get_newsletter_log\")(...)",
    ],
    aliases=[],
)
def get_get_newsletter_log(params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /api/v2/get_newsletter_log."""
    client = get_client()
    return client.get('get_newsletter_log', params=params)
