"""tautulli tool: get_get_date_formats."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="tautulli",
    description="Get the date and time formats used by Tautulli.",
    examples=[
        "load_tool(\"tautulli.get_get_date_formats\")(...)",
    ],
    aliases=[],
)
def get_get_date_formats(params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /api/v2/get_date_formats."""
    client = get_client()
    return client.get('get_date_formats', params=params)
