"""tautulli tool: update_edit_user."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="tautulli",
    description="Update a user on Tautulli.",
    examples=[
        "load_tool(\"tautulli.update_edit_user\")(...)",
    ],
    aliases=[],
)
def update_edit_user(params: Optional[Dict[str, Any]] = None, body: Optional[Any] = None) -> Any:
    """PUT /api/v2/edit_user."""
    client = get_client()
    return client.put('edit_user', body=body, params=params)
