"""tautulli tool: update_update_check."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="tautulli",
    description="Check for Tautulli updates.",
    examples=[
        "load_tool(\"tautulli.update_update_check\")(...)",
    ],
    aliases=[],
)
def update_update_check(params: Optional[Dict[str, Any]] = None, body: Optional[Any] = None) -> Any:
    """PUT /api/v2/update_check."""
    client = get_client()
    return client.put('update_check', body=body, params=params)
