"""radarr tool: create_notification."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="radarr",
    description="POST /api/v3/notification",
    examples=[
        "load_tool(\"radarr.create_notification\")(...)",
    ],
    aliases=[],
)
def create_notification(params: Optional[Dict[str, Any]] = None, body: Optional[Any] = None) -> Any:
    """POST /api/v3/notification."""
    client = get_client()
    return client.post('notification', body=body, params=params)
