"""radarr tool: create_metadata_action_by_name."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="radarr",
    description="POST /api/v3/metadata/action/{name}",
    examples=[
        "load_tool(\"radarr.create_metadata_action_by_name\")(...)",
    ],
    aliases=[],
)
def create_metadata_action_by_name(name: str, params: Optional[Dict[str, Any]] = None, body: Optional[Any] = None) -> Any:
    """POST /api/v3/metadata/action/{name}."""
    client = get_client()
    return client.post(f"metadata/action/{name}", body=body, params=params)
