"""radarr tool: create_system_backup_restore_upload."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="radarr",
    description="POST /api/v3/system/backup/restore/upload",
    examples=[
        "load_tool(\"radarr.create_system_backup_restore_upload\")(...)",
    ],
    aliases=[],
)
def create_system_backup_restore_upload(params: Optional[Dict[str, Any]] = None, body: Optional[Any] = None) -> Any:
    """POST /api/v3/system/backup/restore/upload."""
    client = get_client()
    return client.post('system/backup/restore/upload', body=body, params=params)
