"""radarr tool: create_customformat."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="radarr",
    description="POST /api/v3/customformat",
    examples=[
        "load_tool(\"radarr.create_customformat\")(...)",
    ],
    aliases=[],
)
def create_customformat(params: Optional[Dict[str, Any]] = None, body: Optional[Any] = None) -> Any:
    """POST /api/v3/customformat."""
    client = get_client()
    return client.post('customformat', body=body, params=params)
