"""radarr tool: delete_queue_by_id."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="radarr",
    description="DELETE /api/v3/queue/{id}",
    examples=[
        "load_tool(\"radarr.delete_queue_by_id\")(...)",
    ],
    aliases=[],
)
def delete_queue_by_id(id: int, params: Optional[Dict[str, Any]] = None) -> Any:
    """DELETE /api/v3/queue/{id}."""
    client = get_client()
    return client.delete(f"queue/{id}", params=params)
