"""radarr tool: get_log_file_by_filename."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="radarr",
    description="GET /api/v3/log/file/{filename}",
    examples=[
        "load_tool(\"radarr.get_log_file_by_filename\")(...)",
    ],
    aliases=[],
)
def get_log_file_by_filename(filename: str, params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /api/v3/log/file/{filename}."""
    client = get_client()
    return client.get(f"log/file/{filename}", params=params)
