"""radarr tool: get_wanted_missing."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="radarr",
    description="GET /api/v3/wanted/missing",
    examples=[
        "load_tool(\"radarr.get_wanted_missing\")(...)",
    ],
    aliases=[],
)
def get_wanted_missing(params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /api/v3/wanted/missing."""
    client = get_client()
    return client.get('wanted/missing', params=params)
