"""radarr tool: get_movie_by_id_folder."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="radarr",
    description="GET /api/v3/movie/{id}/folder",
    examples=[
        "load_tool(\"radarr.get_movie_by_id_folder\")(...)",
    ],
    aliases=[],
)
def get_movie_by_id_folder(id: int, params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /api/v3/movie/{id}/folder."""
    client = get_client()
    return client.get(f"movie/{id}/folder", params=params)
