"""Deprecated operation placeholder: get_exclusions."""

from __future__ import annotations

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.
# TODO: deprecated endpoint placeholder for GET /api/v3/exclusions.
# Intentionally no register_tool decorator and no callable.
