"""radarr tool: get_qualityprofile_schema."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="radarr",
    description="GET /api/v3/qualityprofile/schema",
    examples=[
        "load_tool(\"radarr.get_qualityprofile_schema\")(...)",
    ],
    aliases=[],
)
def get_qualityprofile_schema(params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /api/v3/qualityprofile/schema."""
    client = get_client()
    return client.get('qualityprofile/schema', params=params)
