"""radarr tool: get_ping."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="radarr",
    description="GET /ping",
    examples=[
        "load_tool(\"radarr.get_ping\")(...)",
    ],
    aliases=[],
)
def get_ping(params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /ping."""
    client = get_client()
    return client.get('ping', params=params, api_path='')
