"""radarr tool: get_mediacover_by_movie_id_by_filename."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="radarr",
    description="GET /api/v3/mediacover/{movieId}/{filename}",
    examples=[
        "load_tool(\"radarr.get_mediacover_by_movie_id_by_filename\")(...)",
    ],
    aliases=[],
)
def get_mediacover_by_movie_id_by_filename(movie_id: int, filename: str, params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /api/v3/mediacover/{movieId}/{filename}."""
    client = get_client()
    return client.get(f"mediacover/{filename}/{filename}", params=params)
