"""radarr tool: get_queue_status."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="radarr",
    description="GET /api/v3/queue/status",
    examples=[
        "load_tool(\"radarr.get_queue_status\")(...)",
    ],
    aliases=[],
)
def get_queue_status(params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /api/v3/queue/status."""
    client = get_client()
    return client.get('queue/status', params=params)
