"""radarr tool: get_filesystem."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="radarr",
    description="GET /api/v3/filesystem",
    examples=[
        "load_tool(\"radarr.get_filesystem\")(...)",
    ],
    aliases=[],
)
def get_filesystem(params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /api/v3/filesystem."""
    client = get_client()
    return client.get('filesystem', params=params)
