"""radarr tool: get_system_routes."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="radarr",
    description="GET /api/v3/system/routes",
    examples=[
        "load_tool(\"radarr.get_system_routes\")(...)",
    ],
    aliases=[],
)
def get_system_routes(params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /api/v3/system/routes."""
    client = get_client()
    return client.get('system/routes', params=params)
