"""radarr tool: get_movie_lookup_tmdb."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="radarr",
    description="GET /api/v3/movie/lookup/tmdb",
    examples=[
        "load_tool(\"radarr.get_movie_lookup_tmdb\")(...)",
    ],
    aliases=[],
)
def get_movie_lookup_tmdb(params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /api/v3/movie/lookup/tmdb."""
    client = get_client()
    return client.get('movie/lookup/tmdb', params=params)
