"""radarr tool: get_filesystem_mediafiles."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="radarr",
    description="GET /api/v3/filesystem/mediafiles",
    examples=[
        "load_tool(\"radarr.get_filesystem_mediafiles\")(...)",
    ],
    aliases=[],
)
def get_filesystem_mediafiles(params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /api/v3/filesystem/mediafiles."""
    client = get_client()
    return client.get('filesystem/mediafiles', params=params)
