"""radarr tool: update_collection."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="radarr",
    description="PUT /api/v3/collection",
    examples=[
        "load_tool(\"radarr.update_collection\")(...)",
    ],
    aliases=[],
)
def update_collection(params: Optional[Dict[str, Any]] = None, body: Optional[Any] = None) -> Any:
    """PUT /api/v3/collection."""
    client = get_client()
    return client.put('collection', body=body, params=params)
