"""Deprecated operation placeholder: update_moviefile_editor."""

from __future__ import annotations

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.
# TODO: deprecated endpoint placeholder for PUT /api/v3/moviefile/editor.
# Intentionally no register_tool decorator and no callable.
