"""starling tool: create_addresses."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="starling",
    description="Update the account holder's current address",
    examples=[
        "load_tool(\"starling.create_addresses\")(...)",
    ],
    aliases=[],
)
def create_addresses(params: Optional[Dict[str, Any]] = None, body: Optional[Any] = None) -> Any:
    """POST /api/v2/addresses."""
    client = get_client()
    return client.post('addresses', body=body, params=params)
