"""starling tool: delete_payees_by_payee_uid_account_by_account_uid."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="starling",
    description="Delete a payee account",
    examples=[
        "load_tool(\"starling.delete_payees_by_payee_uid_account_by_account_uid\")(...)",
    ],
    aliases=[],
)
def delete_payees_by_payee_uid_account_by_account_uid(payee_uid: str, account_uid: str, params: Optional[Dict[str, Any]] = None) -> Any:
    """DELETE /api/v2/payees/{payeeUid}/account/{accountUid}."""
    client = get_client()
    return client.delete(f"payees/{payee_uid}/account/{account_uid}", params=params)
