"""starling tool: delete_direct_debit_mandates_by_mandate_uid."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="starling",
    description="Cancel the direct debit mandate with the specified identifier",
    examples=[
        "load_tool(\"starling.delete_direct_debit_mandates_by_mandate_uid\")(...)",
    ],
    aliases=[],
)
def delete_direct_debit_mandates_by_mandate_uid(mandate_uid: str, params: Optional[Dict[str, Any]] = None) -> Any:
    """DELETE /api/v2/direct-debit/mandates/{mandateUid}."""
    client = get_client()
    return client.delete(f"direct-debit/mandates/{mandate_uid}", params=params)
