"""starling tool: delete_account_by_account_uid_savings_goals_by_savings_goal_uid."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="starling",
    description="Delete a savings goal",
    examples=[
        "load_tool(\"starling.delete_account_by_account_uid_savings_goals_by_savings_goal_uid\")(...)",
    ],
    aliases=[],
)
def delete_account_by_account_uid_savings_goals_by_savings_goal_uid(account_uid: str, savings_goal_uid: str, params: Optional[Dict[str, Any]] = None) -> Any:
    """DELETE /api/v2/account/{accountUid}/savings-goals/{savingsGoalUid}."""
    client = get_client()
    return client.delete(f"account/{account_uid}/savings-goals/{savings_goal_uid}", params=params)
