"""starling tool: get_account_by_account_uid_spaces_spending_by_space_uid."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="starling",
    description="Get a spending space",
    examples=[
        "load_tool(\"starling.get_account_by_account_uid_spaces_spending_by_space_uid\")(...)",
    ],
    aliases=[],
)
def get_account_by_account_uid_spaces_spending_by_space_uid(account_uid: str, space_uid: str, params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /api/v2/account/{accountUid}/spaces/spending/{spaceUid}."""
    client = get_client()
    return client.get(f"account/{account_uid}/spaces/spending/{space_uid}", params=params)
