"""starling tool: get_direct_debit_mandates."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="starling",
    description="Get a list of direct debit mandates",
    examples=[
        "load_tool(\"starling.get_direct_debit_mandates\")(...)",
    ],
    aliases=[],
)
def get_direct_debit_mandates(params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /api/v2/direct-debit/mandates."""
    client = get_client()
    return client.get('direct-debit/mandates', params=params)
