"""starling tool: get_account_holder_name."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="starling",
    description="Get the name of the account holder",
    examples=[
        "load_tool(\"starling.get_account_holder_name\")(...)",
    ],
    aliases=[],
)
def get_account_holder_name(params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /api/v2/account-holder/name."""
    client = get_client()
    return client.get('account-holder/name', params=params)
