"""starling tool: get_cards."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="starling",
    description="Get all the cards for an account holder",
    examples=[
        "load_tool(\"starling.get_cards\")(...)",
    ],
    aliases=[],
)
def get_cards(params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /api/v2/cards."""
    client = get_client()
    return client.get('cards', params=params)
