"""starling tool: get_payees_by_payee_uid_account_by_account_uid_scheduled_payments."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="starling",
    description="Get scheduled payments",
    examples=[
        "load_tool(\"starling.get_payees_by_payee_uid_account_by_account_uid_scheduled_payments\")(...)",
    ],
    aliases=[],
)
def get_payees_by_payee_uid_account_by_account_uid_scheduled_payments(payee_uid: str, account_uid: str, params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /api/v2/payees/{payeeUid}/account/{accountUid}/scheduled-payments."""
    client = get_client()
    return client.get(f"payees/{payee_uid}/account/{account_uid}/scheduled-payments", params=params)
