"""starling tool: get_accounts."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="starling",
    description="Get the accounts associated with an account holder",
    examples=[
        "load_tool(\"starling.get_accounts\")(...)",
    ],
    aliases=[],
)
def get_accounts(params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /api/v2/accounts."""
    client = get_client()
    return client.get('accounts', params=params)
