"""starling tool: get_feed_account_by_account_uid_category_by_category_uid_by_feed_item_uid_attachments_by_feed_item_attachment_uid."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="starling",
    description="Downloads the feed item attachment",
    examples=[
        "load_tool(\"starling.get_feed_account_by_account_uid_category_by_category_uid_by_feed_item_uid_attachments_by_feed_item_attachment_uid\")(...)",
    ],
    aliases=[],
)
def get_feed_account_by_account_uid_category_by_category_uid_by_feed_item_uid_attachments_by_feed_item_attachment_uid(account_uid: str, category_uid: str, feed_item_uid: str, feed_item_attachment_uid: str, params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /api/v2/feed/account/{accountUid}/category/{categoryUid}/{feedItemUid}/attachments/{feedItemAttachmentUid}."""
    client = get_client()
    return client.get(f"feed/account/{account_uid}/category/{category_uid}/{feed_item_uid}/attachments/{feed_item_attachment_uid}", params=params)
