"""starling tool: get_feed_account_by_account_uid_round_up."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="starling",
    description="Returns the the round-up goal associated with an account if one has been created",
    examples=[
        "load_tool(\"starling.get_feed_account_by_account_uid_round_up\")(...)",
    ],
    aliases=[],
)
def get_feed_account_by_account_uid_round_up(account_uid: str, params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /api/v2/feed/account/{accountUid}/round-up."""
    client = get_client()
    return client.get(f"feed/account/{account_uid}/round-up", params=params)
