"""starling tool: get_identity_token."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="starling",
    description="Get current token identity",
    examples=[
        "load_tool(\"starling.get_identity_token\")(...)",
    ],
    aliases=[],
)
def get_identity_token(params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /api/v2/identity/token."""
    client = get_client()
    return client.get('identity/token', params=params)
