"""starling tool: get_accounts_by_account_uid_identifiers."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="starling",
    description="Get an account's bank identifiers",
    examples=[
        "load_tool(\"starling.get_accounts_by_account_uid_identifiers\")(...)",
    ],
    aliases=[],
)
def get_accounts_by_account_uid_identifiers(account_uid: str, params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /api/v2/accounts/{accountUid}/identifiers."""
    client = get_client()
    return client.get(f"accounts/{account_uid}/identifiers", params=params)
