"""starling tool: get_account_holder_by_account_holder_uid_profile_image."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="starling",
    description="Get a profile image if one exists",
    examples=[
        "load_tool(\"starling.get_account_holder_by_account_holder_uid_profile_image\")(...)",
    ],
    aliases=[],
)
def get_account_holder_by_account_holder_uid_profile_image(account_holder_uid: str, params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /api/v2/account-holder/{accountHolderUid}/profile-image."""
    client = get_client()
    return client.get(f"account-holder/{account_holder_uid}/profile-image", params=params)
