"""starling tool: get_settle_up_profile."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="starling",
    description="Fetch Settle Up profile for an account holder",
    examples=[
        "load_tool(\"starling.get_settle_up_profile\")(...)",
    ],
    aliases=[],
)
def get_settle_up_profile(params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /api/v2/settle-up/profile."""
    client = get_client()
    return client.get('settle-up/profile', params=params)
