"""starling tool: get_direct_debit_mandates_by_mandate_uid_payments."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="starling",
    description="Get a transaction history for a direct debit",
    examples=[
        "load_tool(\"starling.get_direct_debit_mandates_by_mandate_uid_payments\")(...)",
    ],
    aliases=[],
)
def get_direct_debit_mandates_by_mandate_uid_payments(mandate_uid: str, params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /api/v2/direct-debit/mandates/{mandateUid}/payments."""
    client = get_client()
    return client.get(f"direct-debit/mandates/{mandate_uid}/payments", params=params)
