"""starling tool: get_accounts_by_account_uid_feed_export."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="starling",
    description="Download a Feed Export for a given date range",
    examples=[
        "load_tool(\"starling.get_accounts_by_account_uid_feed_export\")(...)",
    ],
    aliases=[],
)
def get_accounts_by_account_uid_feed_export(account_uid: str, params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /api/v2/accounts/{accountUid}/feed-export."""
    client = get_client()
    return client.get(f"accounts/{account_uid}/feed-export", params=params)
