"""starling tool: get_account_by_account_uid_savings_goals."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="starling",
    description="Get all savings goals",
    examples=[
        "load_tool(\"starling.get_account_by_account_uid_savings_goals\")(...)",
    ],
    aliases=[],
)
def get_account_by_account_uid_savings_goals(account_uid: str, params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /api/v2/account/{accountUid}/savings-goals."""
    client = get_client()
    return client.get(f"account/{account_uid}/savings-goals", params=params)
