"""starling tool: get_payees."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="starling",
    description="Get an account holder's payees",
    examples=[
        "load_tool(\"starling.get_payees\")(...)",
    ],
    aliases=[],
)
def get_payees(params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /api/v2/payees."""
    client = get_client()
    return client.get('payees', params=params)
