"""starling tool: get_payments_local_payment_order_by_payment_order_uid."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="starling",
    description="Get a payment order",
    examples=[
        "load_tool(\"starling.get_payments_local_payment_order_by_payment_order_uid\")(...)",
    ],
    aliases=[],
)
def get_payments_local_payment_order_by_payment_order_uid(payment_order_uid: str, params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /api/v2/payments/local/payment-order/{paymentOrderUid}."""
    client = get_client()
    return client.get(f"payments/local/payment-order/{payment_order_uid}", params=params)
