"""starling tool: get_feed_account_by_account_uid_settled_transactions_between."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="starling",
    description="Get the account holder's settled feed items for the specified account, which have settlement time between the two provided timestamps",
    examples=[
        "load_tool(\"starling.get_feed_account_by_account_uid_settled_transactions_between\")(...)",
    ],
    aliases=[],
)
def get_feed_account_by_account_uid_settled_transactions_between(account_uid: str, params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /api/v2/feed/account/{accountUid}/settled-transactions-between."""
    client = get_client()
    return client.get(f"feed/account/{account_uid}/settled-transactions-between", params=params)
