"""starling tool: get_feed_account_by_account_uid_category_by_category_uid_by_feed_item_uid_receipt."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="starling",
    description="Fetches the receipt, created by the registered application, for a given feed item",
    examples=[
        "load_tool(\"starling.get_feed_account_by_account_uid_category_by_category_uid_by_feed_item_uid_receipt\")(...)",
    ],
    aliases=[],
)
def get_feed_account_by_account_uid_category_by_category_uid_by_feed_item_uid_receipt(account_uid: str, category_uid: str, feed_item_uid: str, params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /api/v2/feed/account/{accountUid}/category/{categoryUid}/{feedItemUid}/receipt."""
    client = get_client()
    return client.get(f"feed/account/{account_uid}/category/{category_uid}/{feed_item_uid}/receipt", params=params)
