"""starling tool: get_account_by_account_uid_spaces_by_space_uid_photo."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="starling",
    description="Get the photo associated with a space",
    examples=[
        "load_tool(\"starling.get_account_by_account_uid_spaces_by_space_uid_photo\")(...)",
    ],
    aliases=[],
)
def get_account_by_account_uid_spaces_by_space_uid_photo(account_uid: str, space_uid: str, params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /api/v2/account/{accountUid}/spaces/{spaceUid}/photo."""
    client = get_client()
    return client.get(f"account/{account_uid}/spaces/{space_uid}/photo", params=params)
