"""starling tool: get_payments_local_account_by_account_uid_category_by_category_uid_standing_orders."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="starling",
    description="List standing orders",
    examples=[
        "load_tool(\"starling.get_payments_local_account_by_account_uid_category_by_category_uid_standing_orders\")(...)",
    ],
    aliases=[],
)
def get_payments_local_account_by_account_uid_category_by_category_uid_standing_orders(account_uid: str, category_uid: str, params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /api/v2/payments/local/account/{accountUid}/category/{categoryUid}/standing-orders."""
    client = get_client()
    return client.get(f"payments/local/account/{account_uid}/category/{category_uid}/standing-orders", params=params)
