"""starling tool: get_account_by_account_uid_savings_goals_by_savings_goal_uid_photo."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="starling",
    description="Get the photo associated with a savings goal",
    examples=[
        "load_tool(\"starling.get_account_by_account_uid_savings_goals_by_savings_goal_uid_photo\")(...)",
    ],
    aliases=[],
)
def get_account_by_account_uid_savings_goals_by_savings_goal_uid_photo(account_uid: str, savings_goal_uid: str, params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /api/v2/account/{accountUid}/savings-goals/{savingsGoalUid}/photo."""
    client = get_client()
    return client.get(f"account/{account_uid}/savings-goals/{savings_goal_uid}/photo", params=params)
