"""starling tool: get_feed_account_by_account_uid_category_by_category_uid_paginated_transactions."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="starling",
    description="Get paginated feed items for a category between two timestamps",
    examples=[
        "load_tool(\"starling.get_feed_account_by_account_uid_category_by_category_uid_paginated_transactions\")(...)",
    ],
    aliases=[],
)
def get_feed_account_by_account_uid_category_by_category_uid_paginated_transactions(account_uid: str, category_uid: str, params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /api/v2/feed/account/{accountUid}/category/{categoryUid}/paginated-transactions."""
    client = get_client()
    return client.get(f"feed/account/{account_uid}/category/{category_uid}/paginated-transactions", params=params)
