"""starling tool: get_addresses."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="starling",
    description="Get the account holder's addresses",
    examples=[
        "load_tool(\"starling.get_addresses\")(...)",
    ],
    aliases=[],
)
def get_addresses(params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /api/v2/addresses."""
    client = get_client()
    return client.get('addresses', params=params)
