"""starling tool: get_payees_by_payee_uid_image."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="starling",
    description="Serves the image for the payee",
    examples=[
        "load_tool(\"starling.get_payees_by_payee_uid_image\")(...)",
    ],
    aliases=[],
)
def get_payees_by_payee_uid_image(payee_uid: str, params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /api/v2/payees/{payeeUid}/image."""
    client = get_client()
    return client.get(f"payees/{payee_uid}/image", params=params)
