"""starling tool: update_feed_account_by_account_uid_round_up."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="starling",
    description="Activates transaction round-up and adds remainder to savings goal",
    examples=[
        "load_tool(\"starling.update_feed_account_by_account_uid_round_up\")(...)",
    ],
    aliases=[],
)
def update_feed_account_by_account_uid_round_up(account_uid: str, params: Optional[Dict[str, Any]] = None, body: Optional[Any] = None) -> Any:
    """PUT /api/v2/feed/account/{accountUid}/round-up."""
    client = get_client()
    return client.put(f"feed/account/{account_uid}/round-up", body=body, params=params)
