"""starling tool: update_cards_by_card_uid_controls_currency_switch."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="starling",
    description="Update currency switch payments control",
    examples=[
        "load_tool(\"starling.update_cards_by_card_uid_controls_currency_switch\")(...)",
    ],
    aliases=[],
)
def update_cards_by_card_uid_controls_currency_switch(card_uid: str, params: Optional[Dict[str, Any]] = None, body: Optional[Any] = None) -> Any:
    """PUT /api/v2/cards/{cardUid}/controls/currency-switch."""
    client = get_client()
    return client.put(f"cards/{card_uid}/controls/currency-switch", body=body, params=params)
