"""starling tool: update_payees."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="starling",
    description="Create a payee",
    examples=[
        "load_tool(\"starling.update_payees\")(...)",
    ],
    aliases=[],
)
def update_payees(params: Optional[Dict[str, Any]] = None, body: Optional[Any] = None) -> Any:
    """PUT /api/v2/payees."""
    client = get_client()
    return client.put('payees', body=body, params=params)
