"""starling tool: update_account_by_account_uid_savings_goals_by_savings_goal_uid_withdraw_money_by_transfer_uid."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="starling",
    description="Withdraw money from a savings goal",
    examples=[
        "load_tool(\"starling.update_account_by_account_uid_savings_goals_by_savings_goal_uid_withdraw_money_by_transfer_uid\")(...)",
    ],
    aliases=[],
)
def update_account_by_account_uid_savings_goals_by_savings_goal_uid_withdraw_money_by_transfer_uid(account_uid: str, savings_goal_uid: str, transfer_uid: str, params: Optional[Dict[str, Any]] = None, body: Optional[Any] = None) -> Any:
    """PUT /api/v2/account/{accountUid}/savings-goals/{savingsGoalUid}/withdraw-money/{transferUid}."""
    client = get_client()
    return client.put(f"account/{account_uid}/savings-goals/{savings_goal_uid}/withdraw-money/{transfer_uid}", body=body, params=params)
