"""starling tool: update_payments_local_account_by_account_uid_category_by_category_uid."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="starling",
    description="Create payment",
    examples=[
        "load_tool(\"starling.update_payments_local_account_by_account_uid_category_by_category_uid\")(...)",
    ],
    aliases=[],
)
def update_payments_local_account_by_account_uid_category_by_category_uid(account_uid: str, category_uid: str, params: Optional[Dict[str, Any]] = None, body: Optional[Any] = None) -> Any:
    """PUT /api/v2/payments/local/account/{accountUid}/category/{categoryUid}."""
    client = get_client()
    return client.put(f"payments/local/account/{account_uid}/category/{category_uid}", body=body, params=params)
