"""starling tool: update_identity_logout."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="starling",
    description="Logout the current individual",
    examples=[
        "load_tool(\"starling.update_identity_logout\")(...)",
    ],
    aliases=[],
)
def update_identity_logout(params: Optional[Dict[str, Any]] = None, body: Optional[Any] = None) -> Any:
    """PUT /api/v2/identity/logout."""
    client = get_client()
    return client.put('identity/logout', body=body, params=params)
