"""starling tool: update_account_holder_by_account_holder_uid_profile_image."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="starling",
    description="Update a profile image if one already exists",
    examples=[
        "load_tool(\"starling.update_account_holder_by_account_holder_uid_profile_image\")(...)",
    ],
    aliases=[],
)
def update_account_holder_by_account_holder_uid_profile_image(account_holder_uid: str, params: Optional[Dict[str, Any]] = None, body: Optional[Any] = None) -> Any:
    """PUT /api/v2/account-holder/{accountHolderUid}/profile-image."""
    client = get_client()
    return client.put(f"account-holder/{account_holder_uid}/profile-image", body=body, params=params)
