"""starling tool: update_payees_by_payee_uid_account."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="starling",
    description="Create a payee account",
    examples=[
        "load_tool(\"starling.update_payees_by_payee_uid_account\")(...)",
    ],
    aliases=[],
)
def update_payees_by_payee_uid_account(payee_uid: str, params: Optional[Dict[str, Any]] = None, body: Optional[Any] = None) -> Any:
    """PUT /api/v2/payees/{payeeUid}/account."""
    client = get_client()
    return client.put(f"payees/{payee_uid}/account", body=body, params=params)
