"""starling tool: update_feed_account_by_account_uid_category_by_category_uid_by_feed_item_uid_user_note."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="starling",
    description="Changes the user-specified note attached to a transaction",
    examples=[
        "load_tool(\"starling.update_feed_account_by_account_uid_category_by_category_uid_by_feed_item_uid_user_note\")(...)",
    ],
    aliases=[],
)
def update_feed_account_by_account_uid_category_by_category_uid_by_feed_item_uid_user_note(account_uid: str, category_uid: str, feed_item_uid: str, params: Optional[Dict[str, Any]] = None, body: Optional[Any] = None) -> Any:
    """PUT /api/v2/feed/account/{accountUid}/category/{categoryUid}/{feedItemUid}/user-note."""
    client = get_client()
    return client.put(f"feed/account/{account_uid}/category/{category_uid}/{feed_item_uid}/user-note", body=body, params=params)
