"""starling tool: update_account_by_account_uid_savings_goals."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by nexus-tool-builder/scripts/generate_nexus_toolset.py.

@register_tool(
    namespace="starling",
    description="Create a savings goal",
    examples=[
        "load_tool(\"starling.update_account_by_account_uid_savings_goals\")(...)",
    ],
    aliases=[],
)
def update_account_by_account_uid_savings_goals(account_uid: str, params: Optional[Dict[str, Any]] = None, body: Optional[Any] = None) -> Any:
    """PUT /api/v2/account/{accountUid}/savings-goals."""
    client = get_client()
    return client.put(f"account/{account_uid}/savings-goals", body=body, params=params)
