"""Sonarr tool: create_series_import."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by tools/sonarr/generate_tools.py.

@register_tool(
    namespace="sonarr",
    description="POST /api/v3/series/import",
    examples=[
        "load_tool(\"sonarr.create_series_import\")(...)",
    ],
    aliases=[],
)
def create_series_import(params: Optional[Dict[str, Any]] = None, body: Optional[Any] = None) -> Any:
    """POST /api/v3/series/import."""
    client = get_client()
    return client.post('series/import', body=body, params=params)
