"""Sonarr tool: create_command."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by tools/sonarr/generate_tools.py.

@register_tool(
    namespace="sonarr",
    description="POST /api/v3/command",
    examples=[
        "load_tool(\"sonarr.create_command\")(...)",
    ],
    aliases=["sonarr.run_command", "run_command"],
)
def create_command(params: Optional[Dict[str, Any]] = None, body: Optional[Any] = None) -> Any:
    """POST /api/v3/command."""
    client = get_client()
    return client.post('command', body=body, params=params)
