"""Sonarr tool: create_release_push."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by tools/sonarr/generate_tools.py.

@register_tool(
    namespace="sonarr",
    description="POST /api/v3/release/push",
    examples=[
        "load_tool(\"sonarr.create_release_push\")(...)",
    ],
    aliases=[],
)
def create_release_push(params: Optional[Dict[str, Any]] = None, body: Optional[Any] = None) -> Any:
    """POST /api/v3/release/push."""
    client = get_client()
    return client.post('release/push', body=body, params=params)
