"""Sonarr tool: create_history_failed_by_id."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by tools/sonarr/generate_tools.py.

@register_tool(
    namespace="sonarr",
    description="POST /api/v3/history/failed/{id}",
    examples=[
        "load_tool(\"sonarr.create_history_failed_by_id\")(...)",
    ],
    aliases=[],
)
def create_history_failed_by_id(id: int, params: Optional[Dict[str, Any]] = None, body: Optional[Any] = None) -> Any:
    """POST /api/v3/history/failed/{id}."""
    client = get_client()
    return client.post(f"history/failed/{id}", body=body, params=params)
