"""Sonarr tool: create_rootfolder."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by tools/sonarr/generate_tools.py.

@register_tool(
    namespace="sonarr",
    description="POST /api/v3/rootfolder",
    examples=[
        "load_tool(\"sonarr.create_rootfolder\")(...)",
    ],
    aliases=[],
)
def create_rootfolder(params: Optional[Dict[str, Any]] = None, body: Optional[Any] = None) -> Any:
    """POST /api/v3/rootfolder."""
    client = get_client()
    return client.post('rootfolder', body=body, params=params)
