"""Sonarr tool: delete_indexer_bulk."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by tools/sonarr/generate_tools.py.

@register_tool(
    namespace="sonarr",
    description="DELETE /api/v3/indexer/bulk",
    examples=[
        "load_tool(\"sonarr.delete_indexer_bulk\")(...)",
    ],
    aliases=[],
)
def delete_indexer_bulk(params: Optional[Dict[str, Any]] = None) -> Any:
    """DELETE /api/v3/indexer/bulk."""
    client = get_client()
    return client.delete('indexer/bulk', params=params)
