"""Sonarr tool: delete_metadata_by_id."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by tools/sonarr/generate_tools.py.

@register_tool(
    namespace="sonarr",
    description="DELETE /api/v3/metadata/{id}",
    examples=[
        "load_tool(\"sonarr.delete_metadata_by_id\")(...)",
    ],
    aliases=[],
)
def delete_metadata_by_id(id: int, params: Optional[Dict[str, Any]] = None) -> Any:
    """DELETE /api/v3/metadata/{id}."""
    client = get_client()
    return client.delete(f"metadata/{id}", params=params)
