"""Generate deterministic Sonarr tool plans and per-tool modules from OpenAPI."""

from __future__ import annotations

import argparse
import json
import keyword
import re
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any

HTTP_METHOD_ORDER = {
    "get": 0,
    "post": 1,
    "put": 2,
    "delete": 3,
    "head": 4,
}

METHOD_PREFIX = {
    "get": "get",
    "post": "create",
    "put": "update",
    "delete": "delete",
    "head": "head",
}

CLIENT_METHOD_BY_HTTP = {
    "GET": "get",
    "POST": "post",
    "PUT": "put",
    "DELETE": "delete",
    "HEAD": "head",
}

TYPE_BY_OPENAPI = {
    "string": "str",
    "integer": "int",
    "number": "float",
    "boolean": "bool",
}

PATH_PARAM_RE = re.compile(r"^\{([^{}]+)\}$")
NON_ALNUM_RE = re.compile(r"[^A-Za-z0-9]+")
UNDERSCORE_RE = re.compile(r"_+")
CAMEL_BOUNDARY_RE_1 = re.compile(r"([a-z0-9])([A-Z])")
CAMEL_BOUNDARY_RE_2 = re.compile(r"([A-Z]+)([A-Z][a-z])")
GENERATED_HEADER = "# This file is auto-generated by tools/sonarr/generate_tools.py."

LEGACY_ALIASES_BY_CANONICAL_NAME: dict[str, list[str]] = {
    "get_series_lookup": ["sonarr.lookup_series", "lookup_series"],
    "create_series": ["sonarr.add_series", "add_series"],
    "update_series_by_id": ["sonarr.update_series", "update_series"],
    "delete_series_by_id": ["sonarr.delete_series", "delete_series"],
    "create_command": ["sonarr.run_command", "run_command"],
    "get_rootfolder": ["sonarr.get_root_folders", "get_root_folders"],
    "get_qualityprofile": ["sonarr.get_quality_profiles", "get_quality_profiles"],
}


@dataclass(frozen=True)
class OperationPlan:
    method: str
    path: str
    name: str
    deprecated: bool
    source: str
    operation_id: str | None
    summary: str | None


def sanitize_token(value: str) -> str:
    """Normalize arbitrary text into a snake_case token."""
    normalized = value.strip()
    normalized = CAMEL_BOUNDARY_RE_2.sub(r"\1_\2", normalized)
    normalized = CAMEL_BOUNDARY_RE_1.sub(r"\1_\2", normalized)
    cleaned = NON_ALNUM_RE.sub("_", normalized.lower())
    cleaned = UNDERSCORE_RE.sub("_", cleaned).strip("_")
    return cleaned


def ensure_python_identifier(value: str, default: str = "op") -> str:
    """Ensure a safe Python identifier, preserving determinism."""
    token = sanitize_token(value)
    if not token:
        token = default
    if token[0].isdigit():
        token = f"_{token}"
    if keyword.iskeyword(token):
        token = f"{token}_"
    return token


def normalize_path_segment(segment: str) -> str:
    """Convert a raw path segment to a deterministic name component."""
    match = PATH_PARAM_RE.match(segment)
    if match:
        param = ensure_python_identifier(match.group(1), default="param")
        return f"by_{param}"
    return ensure_python_identifier(segment, default="segment")


def iter_name_segments(path: str) -> list[str]:
    """Build normalized path-derived segments with /api/v3 stripped from names."""
    if path == "/ping":
        return ["ping"]

    stripped = path
    if stripped.startswith("/api/v3"):
        stripped = stripped[len("/api/v3") :]

    stripped = stripped.strip("/")
    if not stripped:
        return []

    return [normalize_path_segment(segment) for segment in stripped.split("/") if segment]


def build_operation_name(method: str, path: str) -> str:
    """Create the stable canonical function name for a method/path."""
    method_key = method.lower()
    prefix = METHOD_PREFIX[method_key]
    segments = iter_name_segments(path)
    base = "_".join([prefix, *segments]) if segments else prefix
    return ensure_python_identifier(base, default=f"{prefix}_op")


def is_supported_path(path: str) -> bool:
    return path == "/ping" or path.startswith("/api/v3/")


def is_supported_method(method: str) -> bool:
    return method.lower() in METHOD_PREFIX


def build_plan(spec: dict[str, Any], source: str) -> tuple[list[OperationPlan], list[OperationPlan]]:
    """Return deterministic canonical/deprecated operation plans."""
    canonical: list[OperationPlan] = []
    deprecated: list[OperationPlan] = []

    paths = spec.get("paths")
    if not isinstance(paths, dict):
        raise ValueError("OpenAPI document missing object at paths")

    for path, path_item in sorted(paths.items()):
        if not is_supported_path(path):
            continue
        if not isinstance(path_item, dict):
            continue

        for method, operation in sorted(
            path_item.items(),
            key=lambda item: (
                HTTP_METHOD_ORDER.get(item[0].lower(), 999),
                item[0].lower(),
            ),
        ):
            if not is_supported_method(method):
                continue
            if not isinstance(operation, dict):
                continue

            plan_item = OperationPlan(
                method=method.upper(),
                path=path,
                name=build_operation_name(method, path),
                deprecated=bool(operation.get("deprecated", False)),
                source=source,
                operation_id=operation.get("operationId"),
                summary=operation.get("summary"),
            )
            if plan_item.deprecated:
                deprecated.append(plan_item)
            else:
                canonical.append(plan_item)

    canonical.sort(
        key=lambda item: (
            item.path,
            HTTP_METHOD_ORDER.get(item.method.lower(), 999),
            item.method,
            item.name,
        )
    )
    deprecated.sort(
        key=lambda item: (
            item.path,
            HTTP_METHOD_ORDER.get(item.method.lower(), 999),
            item.method,
            item.name,
        )
    )
    return canonical, deprecated


def plan_to_dict(canonical: list[OperationPlan], deprecated: list[OperationPlan]) -> dict[str, Any]:
    return {
        "canonical": [asdict(item) for item in canonical],
        "deprecated": [asdict(item) for item in deprecated],
    }


def write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def collect_path_parameters(operation: dict[str, Any], path_item: dict[str, Any]) -> list[dict[str, Any]]:
    params: list[dict[str, Any]] = []

    for candidate in [path_item.get("parameters"), operation.get("parameters")]:
        if not isinstance(candidate, list):
            continue
        for param in candidate:
            if isinstance(param, dict):
                params.append(param)

    selected: dict[str, dict[str, Any]] = {}
    for param in params:
        if param.get("in") != "path":
            continue
        if not param.get("required", False):
            continue
        name = param.get("name")
        if isinstance(name, str) and name:
            selected[name] = param

    ordered: list[dict[str, Any]] = []
    for segment in operation.get("x-path-order", []):
        if segment in selected:
            ordered.append(selected.pop(segment))
    ordered.extend(selected[name] for name in sorted(selected))
    return ordered


def extract_path_param_order(path: str) -> list[str]:
    names: list[str] = []
    for segment in path.split("/"):
        match = PATH_PARAM_RE.match(segment)
        if match:
            names.append(match.group(1))
    return names


def python_type_for_param(param: dict[str, Any]) -> str:
    schema = param.get("schema")
    if isinstance(schema, dict):
        schema_type = schema.get("type")
        if isinstance(schema_type, str):
            return TYPE_BY_OPENAPI.get(schema_type, "Any")
    return "Any"


def endpoint_expr(path: str) -> tuple[str, set[str]]:
    endpoint = path
    if endpoint.startswith("/api/v3/"):
        endpoint = endpoint[len("/api/v3/") :]
    endpoint = endpoint.lstrip("/")

    tokens: list[str] = []
    path_params: set[str] = set()
    for segment in endpoint.split("/"):
        match = PATH_PARAM_RE.match(segment)
        if match:
            param_name = ensure_python_identifier(match.group(1), default="param")
            tokens.append("{" + param_name + "}")
            path_params.add(param_name)
        else:
            tokens.append(segment)

    expr = "/".join(tokens)
    if path_params:
        return f'f"{expr}"', path_params
    return repr(expr), path_params


def decorator_description(plan_item: OperationPlan) -> str:
    summary = (plan_item.summary or "").strip()
    if summary:
        return summary
    return f"{plan_item.method} {plan_item.path}"


def canonical_module_text(
    plan_item: OperationPlan,
    operation: dict[str, Any],
    path_item: dict[str, Any],
) -> str:
    method = plan_item.method
    client_method = CLIENT_METHOD_BY_HTTP.get(method)
    if client_method is None:
        raise ValueError(f"Unsupported canonical HTTP method: {method}")

    operation = dict(operation)
    operation["x-path-order"] = extract_path_param_order(plan_item.path)
    path_params = collect_path_parameters(operation, path_item)

    endpoint, endpoint_params = endpoint_expr(plan_item.path)

    has_body = method in {"POST", "PUT"}
    include_params_arg = True

    imports = {"Any"}
    if include_params_arg:
        imports.update({"Dict", "Optional"})
    if has_body:
        imports.add("Optional")

    arg_parts: list[str] = []
    for param in path_params:
        raw_name = str(param.get("name"))
        py_name = ensure_python_identifier(raw_name, default="param")
        if py_name not in endpoint_params:
            continue
        py_type = python_type_for_param(param)
        if py_type == "Any":
            imports.add("Any")
        arg_parts.append(f"{py_name}: {py_type}")

    if include_params_arg:
        arg_parts.append("params: Optional[Dict[str, Any]] = None")
    if has_body:
        arg_parts.append("body: Optional[Any] = None")

    signature = ", ".join(arg_parts)

    body_lines = ["    client = get_client()"]
    api_path_override = ", api_path=''" if not plan_item.path.startswith("/api/v3/") else ""
    if method in {"GET", "DELETE", "HEAD"}:
        body_lines.append(
            f"    return client.{client_method}({endpoint}, params=params{api_path_override})"
        )
    elif method in {"POST", "PUT"}:
        body_lines.append(
            f"    return client.{client_method}({endpoint}, body=body, params=params{api_path_override})"
        )
    else:
        body_lines.append(f"    return client.{client_method}({endpoint})")

    imports_line = ", ".join(sorted(imports, key=lambda t: (t != "Any", t)))
    description_literal = json.dumps(decorator_description(plan_item))
    example_literal = json.dumps(f'load_tool("sonarr.{plan_item.name}")(...)')
    aliases = LEGACY_ALIASES_BY_CANONICAL_NAME.get(plan_item.name, [])
    aliases_literal = json.dumps(aliases)

    lines = [
        f'"""Sonarr tool: {plan_item.name}."""',
        "",
        "from __future__ import annotations",
        "",
        f"from typing import {imports_line}",
        "",
        "from nexus.tool_registry import register_tool",
        "",
        "from .client import get_client",
        "",
        GENERATED_HEADER,
        "",
        "@register_tool(",
        "    namespace=\"sonarr\",",
        f"    description={description_literal},",
        "    examples=[",
        f"        {example_literal},",
        "    ],",
        f"    aliases={aliases_literal},",
        ")",
        f"def {plan_item.name}({signature}) -> Any:",
        f'    """{plan_item.method} {plan_item.path}."""',
        *body_lines,
        "",
    ]
    return "\n".join(lines)


def deprecated_placeholder_text(plan_item: OperationPlan) -> str:
    lines = [
        f'"""Deprecated Sonarr operation placeholder: {plan_item.name}."""',
        "",
        "from __future__ import annotations",
        "",
        GENERATED_HEADER,
        "",
        f"# TODO: Deprecated Sonarr endpoint placeholder for {plan_item.method} {plan_item.path}.",
        "# Intentionally no register_tool decorator and no callable implementation.",
        "",
    ]
    return "\n".join(lines)


def write_if_changed(path: Path, content: str) -> None:
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return
    path.write_text(content, encoding="utf-8")


def canonical_module_filename(plan_item: OperationPlan) -> str:
    """Return deterministic canonical module filename for a plan item."""
    if plan_item.name.endswith("_test"):
        return f"{plan_item.name}_tool.py"
    return f"{plan_item.name}.py"


def generate_modules(
    spec: dict[str, Any],
    canonical: list[OperationPlan],
    deprecated: list[OperationPlan],
    module_dir: Path,
) -> tuple[list[Path], list[Path], list[Path]]:
    module_dir.mkdir(parents=True, exist_ok=True)

    paths = spec.get("paths")
    if not isinstance(paths, dict):
        raise ValueError("OpenAPI document missing object at paths")

    canonical_paths: list[Path] = []
    deprecated_paths: list[Path] = []

    for plan_item in sorted(canonical, key=lambda item: item.name):
        path_item = paths.get(plan_item.path)
        if not isinstance(path_item, dict):
            raise ValueError(f"Missing path item for {plan_item.path}")
        operation = path_item.get(plan_item.method.lower())
        if not isinstance(operation, dict):
            raise ValueError(f"Missing operation object for {plan_item.method} {plan_item.path}")
        file_path = module_dir / canonical_module_filename(plan_item)
        write_if_changed(file_path, canonical_module_text(plan_item, operation, path_item))
        canonical_paths.append(file_path)

    for plan_item in sorted(deprecated, key=lambda item: item.name):
        file_path = module_dir / f"{plan_item.name}.py"
        write_if_changed(file_path, deprecated_placeholder_text(plan_item))
        deprecated_paths.append(file_path)

    keep = {
        "__init__.py",
        "client.py",
        "generate_tools.py",
        "api.py",
    }
    keep.update(path.name for path in canonical_paths)
    keep.update(path.name for path in deprecated_paths)

    removed: list[Path] = []
    for py_file in sorted(module_dir.glob("*.py")):
        if py_file.name in keep:
            continue
        py_file.unlink()
        removed.append(py_file)

    return canonical_paths, deprecated_paths, removed


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--spec",
        type=Path,
        default=Path(__file__).with_name("v3.json"),
        help="Path to Sonarr OpenAPI v3.json",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=None,
        help="Optional path for combined canonical/deprecated plan JSON",
    )
    parser.add_argument(
        "--canonical-out",
        type=Path,
        default=None,
        help="Optional path for canonical-only plan JSON",
    )
    parser.add_argument(
        "--deprecated-out",
        type=Path,
        default=None,
        help="Optional path for deprecated-only plan JSON",
    )
    parser.add_argument(
        "--write-modules",
        action="store_true",
        help="Write per-tool module files under --module-dir",
    )
    parser.add_argument(
        "--module-dir",
        type=Path,
        default=Path(__file__).parent,
        help="Directory where per-tool module files are written",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    spec_text = args.spec.read_text(encoding="utf-8")
    spec = json.loads(spec_text)

    canonical, deprecated = build_plan(spec, source=str(args.spec))
    combined = plan_to_dict(canonical, deprecated)

    if args.out is not None:
        write_json(args.out, combined)
    if args.canonical_out is not None:
        write_json(args.canonical_out, {"canonical": combined["canonical"]})
    if args.deprecated_out is not None:
        write_json(args.deprecated_out, {"deprecated": combined["deprecated"]})

    if args.write_modules:
        canonical_paths, deprecated_paths, removed_paths = generate_modules(
            spec=spec,
            canonical=canonical,
            deprecated=deprecated,
            module_dir=args.module_dir,
        )
        print(
            json.dumps(
                {
                    "written_canonical": len(canonical_paths),
                    "written_deprecated": len(deprecated_paths),
                    "removed": [str(path) for path in removed_paths],
                },
                indent=2,
                sort_keys=True,
            )
        )

    if (
        args.out is None
        and args.canonical_out is None
        and args.deprecated_out is None
        and not args.write_modules
    ):
        print(json.dumps(combined, indent=2, sort_keys=True))

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
