"""Sonarr tool: get_rename."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by tools/sonarr/generate_tools.py.

@register_tool(
    namespace="sonarr",
    description="GET /api/v3/rename",
    examples=[
        "load_tool(\"sonarr.get_rename\")(...)",
    ],
    aliases=[],
)
def get_rename(params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /api/v3/rename."""
    client = get_client()
    return client.get('rename', params=params)
