"""Deprecated Sonarr operation placeholder: get_languageprofile."""

from __future__ import annotations

# This file is auto-generated by tools/sonarr/generate_tools.py.

# TODO: Deprecated Sonarr endpoint placeholder for GET /api/v3/languageprofile.
# Intentionally no register_tool decorator and no callable implementation.
