"""Sonarr tool: get_mediacover_by_series_id_by_filename."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by tools/sonarr/generate_tools.py.

@register_tool(
    namespace="sonarr",
    description="GET /api/v3/mediacover/{seriesId}/{filename}",
    examples=[
        "load_tool(\"sonarr.get_mediacover_by_series_id_by_filename\")(...)",
    ],
    aliases=[],
)
def get_mediacover_by_series_id_by_filename(series_id: int, filename: str, params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /api/v3/mediacover/{seriesId}/{filename}."""
    client = get_client()
    return client.get(f"mediacover/{series_id}/{filename}", params=params)
