"""Sonarr tool: get_wanted_cutoff."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by tools/sonarr/generate_tools.py.

@register_tool(
    namespace="sonarr",
    description="GET /api/v3/wanted/cutoff",
    examples=[
        "load_tool(\"sonarr.get_wanted_cutoff\")(...)",
    ],
    aliases=[],
)
def get_wanted_cutoff(params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /api/v3/wanted/cutoff."""
    client = get_client()
    return client.get('wanted/cutoff', params=params)
