"""Sonarr tool: get_series_by_id_folder."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by tools/sonarr/generate_tools.py.

@register_tool(
    namespace="sonarr",
    description="GET /api/v3/series/{id}/folder",
    examples=[
        "load_tool(\"sonarr.get_series_by_id_folder\")(...)",
    ],
    aliases=[],
)
def get_series_by_id_folder(id: int, params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /api/v3/series/{id}/folder."""
    client = get_client()
    return client.get(f"series/{id}/folder", params=params)
