"""Sonarr tool: get_autotagging."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by tools/sonarr/generate_tools.py.

@register_tool(
    namespace="sonarr",
    description="GET /api/v3/autotagging",
    examples=[
        "load_tool(\"sonarr.get_autotagging\")(...)",
    ],
    aliases=[],
)
def get_autotagging(params: Optional[Dict[str, Any]] = None) -> Any:
    """GET /api/v3/autotagging."""
    client = get_client()
    return client.get('autotagging', params=params)
