"""Sonarr tool: update_config_host_by_id."""

from __future__ import annotations

from typing import Any, Dict, Optional

from nexus.tool_registry import register_tool

from .client import get_client

# This file is auto-generated by tools/sonarr/generate_tools.py.

@register_tool(
    namespace="sonarr",
    description="PUT /api/v3/config/host/{id}",
    examples=[
        "load_tool(\"sonarr.update_config_host_by_id\")(...)",
    ],
    aliases=[],
)
def update_config_host_by_id(id: str, params: Optional[Dict[str, Any]] = None, body: Optional[Any] = None) -> Any:
    """PUT /api/v3/config/host/{id}."""
    client = get_client()
    return client.put(f"config/host/{id}", body=body, params=params)
