"""Deprecated Sonarr operation placeholder: update_languageprofile_by_id."""

from __future__ import annotations

# This file is auto-generated by tools/sonarr/generate_tools.py.

# TODO: Deprecated Sonarr endpoint placeholder for PUT /api/v3/languageprofile/{id}.
# Intentionally no register_tool decorator and no callable implementation.
